/* =================================================================
   Gharîb — Inhalte (Kategorien · Begriffe · Nasîha-Bibliothek)

   WICHTIG (Amâna / Verantwortung vor Allah):
   - Alle Verse sind mit Sûra + Âya angegeben.
   - Hadithe stammen ausschließlich aus anerkannt authentischen
     Sammlungen (Ṣaḥîḥ al-Bukhârî / Ṣaḥîḥ Muslim) und sind mit
     Nummer und Grad (Ṣaḥîḥ) angegeben.
   - Der arabische Text ist der Originaltext; die anderen Sprachen
     sind sinngemäße Übersetzungen.
   Neue Begriffe lassen sich unten einfach ergänzen.
   ================================================================= */

/* ---------- Icons (reine Geometrie, keine Lebewesen) ---------- */
const ICONS = {
  prophets: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 2l2.2 4.6 5 .7-3.6 3.5.9 5L12 18l-4.5 2.3.9-5L4.8 7.3l5-.7z"/></svg>',
  companions: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><circle cx="12" cy="8" r="3"/><circle cx="6" cy="15" r="2.4"/><circle cx="18" cy="15" r="2.4"/></svg>',
  worship: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M6 21V11a6 6 0 0 1 12 0v10"/><path d="M4 21h16"/><path d="M12 11v10"/></svg>',
  quran: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 6c-1.8-1.3-4-2-6.5-2A2.5 2.5 0 0 0 3 6.5v11A1.5 1.5 0 0 0 4.5 19c2.4 0 4.6.6 6.5 2 1.9-1.4 4.1-2 6.5-2A1.5 1.5 0 0 0 21 17.5v-11A2.5 2.5 0 0 0 18.5 4C16 4 13.8 4.7 12 6z"/><path d="M12 6v15"/></svg>',
  places: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M4 8l8-4 8 4v11H4z"/><path d="M4 8l8 3 8-3"/><path d="M12 11v8"/></svg>',
  akhlaq: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 20s-7-4.3-9-9.2C1.8 7.5 3.6 4.8 6.6 4.8c1.9 0 3.3 1 4.4 2.6 1.1-1.6 2.5-2.6 4.4-2.6 3 0 4.8 2.7 3.6 6C19 15.7 12 20 12 20z"/></svg>',
  mixed: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 3l2.5 5.5L20 11l-5.5 2.5L12 19l-2.5-5.5L4 11l5.5-2.5z"/></svg>',
  aqida: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5z"/><path d="M18.5 3.2l.6 1.6 1.6.6-1.6.6-.6 1.6-.6-1.6-1.6-.6 1.6-.6z"/></svg>',
  history: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M5 4h9a2 2 0 0 1 2 2v13a1 1 0 0 0 1 1H8a3 3 0 0 1-3-3z"/><path d="M8 8h5M8 12h5"/></svg>',
  quiz: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.3 9.2a2.7 2.7 0 0 1 5.2 1c0 1.9-2.6 2.2-2.6 3.9"/><path d="M12 17.1v.1"/></svg>',
  objects: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="4" y="8" width="16" height="12" rx="2"/><path d="M4 12h16M9 8V6h6v2"/></svg>',
  animals: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M5 20c0-9 6-15 15-15 0 9-6 15-15 15z"/><path d="M6 19c4-5 8-8 12-9"/></svg>',
  food: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 8c-1.2-2.2-3.4-3-5.4-2C3.7 7.4 3.7 12 6 15c1.5 2 3 3.6 6 3.6s4.5-1.6 6-3.6c2.3-3 2.3-7.6-.6-9-2-1-4.2-.2-5.4 2z"/><path d="M12 8V4.5c.8-1 1.9-1.3 3-1.1"/></svg>',
  jobs: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M15.5 7.5a3.4 3.4 0 0 0-4.6 4.2l-5.6 5.6a1.6 1.6 0 0 0 2.2 2.2l5.6-5.6a3.4 3.4 0 0 0 4.2-4.6l-2.3 2.3-1.8-1.8z"/></svg>',
  baddeeds: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M6 6l12 12"/></svg>',
  star8: '<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M50 6l10 14 16-6-2 17 14 10-14 10 2 17-16-6-10 14-10-14-16 6 2-17L14 51l14-10-2-17 16 6z"/><circle cx="50" cy="50" r="13"/></svg>',
};

/* ---------- Kategorien ---------- */
const CATEGORIES = [
  { id: 'prophets',   icon: ICONS.prophets,   name: { de: 'Propheten',   tr: 'Peygamberler', en: 'Prophets',   ar: 'الأنبياء' } },
  { id: 'companions', icon: ICONS.companions, name: { de: 'Gefährten',   tr: 'Sahabeler',    en: 'Companions', ar: 'الصحابة' } },
  { id: 'worship',    icon: ICONS.worship,    name: { de: 'Gottesdienst',tr: 'İbadet',       en: 'Worship',    ar: 'العبادات' } },
  { id: 'quran',      icon: ICONS.quran,      name: { de: 'Qurʾân & Suren', tr: 'Kurʾân & Sureler', en: 'Qurʾân & Surahs', ar: 'القرآن والسور' } },
  { id: 'places',     icon: ICONS.places,     name: { de: 'Heilige Orte',tr: 'Kutsal Yerler',en: 'Sacred Places', ar: 'الأماكن المقدسة' } },
  { id: 'akhlaq',     icon: ICONS.akhlaq,     name: { de: 'Charakter',   tr: 'Ahlak',        en: 'Character',  ar: 'الأخلاق' } },
  { id: 'aqida',      icon: ICONS.aqida,      name: { de: 'Glaube & Jenseits', tr: 'İman & Ahiret', en: 'Faith & Hereafter', ar: 'العقيدة والآخرة' } },
  { id: 'history',    icon: ICONS.history,    name: { de: 'Sîra & Geschichte', tr: 'Siyer & Tarih', en: 'Sîrah & History', ar: 'السيرة والتاريخ' } },
  { id: 'objects',    icon: ICONS.objects,    name: { de: 'Gegenstände', tr: 'Eşyalar',   en: 'Objects', ar: 'أشياء' } },
  { id: 'animals',    icon: ICONS.animals,    name: { de: 'Tiere',       tr: 'Hayvanlar', en: 'Animals', ar: 'حيوانات' } },
  { id: 'food',       icon: ICONS.food,       name: { de: 'Obst, Gemüse & Speisen', tr: 'Meyve, sebze & yiyecek', en: 'Food', ar: 'أطعمة' } },
  { id: 'jobs',       icon: ICONS.jobs,       name: { de: 'Berufe',      tr: 'Meslekler', en: 'Professions', ar: 'مهن' } },
  { id: 'people',     icon: ICONS.companions, name: { de: 'Menschen',    tr: 'İnsanlar',  en: 'People', ar: 'أشخاص' } },
  { id: 'good_deeds', icon: ICONS.akhlaq,     name: { de: 'Gute Taten',  tr: 'Güzel ameller', en: 'Good deeds', ar: 'أعمال صالحة' } },
  { id: 'bad_deeds',  icon: ICONS.baddeeds,   name: { de: 'Sünden & Harâm', tr: 'Günah & Haram', en: 'Sins & Ḥarâm', ar: 'ذنوب ومحرمات' } },
];

/* ---------- Nasîha-Bibliothek (belegte Verse & Hadithe) ---------- */
const NASIHA = {
  /* --- Verse (Qurʾân) --- */
  tawhid: { type: 'verse', ref: 'al-Ikhlâṣ 112:1–4',
    ar: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    de: '„Sprich: Er ist Allah, ein Einziger. Allah, der Absolute, auf den alles angewiesen ist. Er zeugt nicht und ist nicht gezeugt worden, und niemand ist Ihm gleich.“',
    tr: '„De ki: O Allah birdir. Allah Samed’dir. Doğurmamış ve doğmamıştır. Hiçbir şey O’na denk değildir.“',
    en: '“Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, and there is none comparable to Him.”' },

  worship_purpose: { type: 'verse', ref: 'adh-Dhâriyât 51:56',
    ar: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ',
    de: '„Und Ich habe die Ǧinn und die Menschen nur dazu erschaffen, dass sie Mir dienen.“',
    tr: '„Ben cinleri ve insanları ancak bana kulluk etsinler diye yarattım.“',
    en: '“And I did not create the jinn and mankind except to worship Me.”' },

  salah: { type: 'verse', ref: 'al-ʿAnkabût 29:45',
    ar: 'إِنَّ الصَّلَاةَ تَنْهَىٰ عَنِ الْفَحْشَاءِ وَالْمُنكَرِ',
    de: '„Wahrlich, das Gebet hält von dem Schändlichen und dem Verwerflichen ab.“',
    tr: '„Şüphesiz namaz, hayâsızlıktan ve kötülükten alıkoyar.“',
    en: '“Indeed, prayer restrains from immorality and wrongdoing.”' },

  zakat_salah: { type: 'verse', ref: 'al-Baqara 2:43',
    ar: 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ وَارْكَعُوا مَعَ الرَّاكِعِينَ',
    de: '„Und verrichtet das Gebet, entrichtet die Zakât und verneigt euch mit den sich Verneigenden.“',
    tr: '„Namazı kılın, zekâtı verin ve rükû edenlerle birlikte rükû edin.“',
    en: '“And establish prayer, give zakah, and bow with those who bow.”' },

  sawm: { type: 'verse', ref: 'al-Baqara 2:183',
    ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ كَمَا كُتِبَ عَلَى الَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ',
    de: '„O die ihr glaubt, vorgeschrieben ist euch das Fasten, so wie es denen vor euch vorgeschrieben war, auf dass ihr gottesfürchtig werdet.“',
    tr: '„Ey iman edenler! Sizden öncekilere farz kılındığı gibi oruç size de farz kılındı; umulur ki sakınırsınız.“',
    en: '“O you who believe, fasting is prescribed for you as it was for those before you, that you may become mindful of Allah.”' },

  hajj: { type: 'verse', ref: 'Âl ʿImrân 3:97',
    ar: 'وَلِلَّهِ عَلَى النَّاسِ حِجُّ الْبَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا',
    de: '„Und Allah steht den Menschen gegenüber die Pilgerfahrt zum Haus zu – wer einen Weg dorthin finden kann.“',
    tr: '„Yoluna gücü yetenlerin o evi (Kâbe’yi) haccetmesi, Allah’ın insanlar üzerindeki hakkıdır.“',
    en: '“And pilgrimage to the House is a duty owed to Allah by those able to find a way to it.”' },

  knowledge: { type: 'verse', ref: 'Ṭâ Hâ 20:114',
    ar: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
    de: '„Und sag: Mein Herr, mehre mir mein Wissen.“',
    tr: '„De ki: Rabbim, ilmimi artır.“',
    en: '“And say: My Lord, increase me in knowledge.”' },

  first_revelation: { type: 'verse', ref: 'al-ʿAlaq 96:1',
    ar: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',
    de: '„Lies im Namen deines Herrn, Der erschaffen hat.“',
    tr: '„Yaratan Rabbinin adıyla oku.“',
    en: '“Read in the name of your Lord who created.”' },

  sabr: { type: 'verse', ref: 'al-Baqara 2:153',
    ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    de: '„O die ihr glaubt, sucht Hilfe in der Geduld und im Gebet. Wahrlich, Allah ist mit den Geduldigen.“',
    tr: '„Ey iman edenler! Sabır ve namazla yardım dileyin. Şüphesiz Allah, sabredenlerle beraberdir.“',
    en: '“O you who believe, seek help through patience and prayer. Indeed, Allah is with the patient.”' },

  ease: { type: 'verse', ref: 'ash-Sharḥ 94:5–6',
    ar: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
    de: '„Denn mit der Erschwernis kommt Erleichterung. Wahrlich, mit der Erschwernis kommt Erleichterung.“',
    tr: '„Şüphesiz zorlukla beraber bir kolaylık vardır. Gerçekten zorlukla beraber bir kolaylık vardır.“',
    en: '“For indeed, with hardship comes ease. Indeed, with hardship comes ease.”' },

  shukr: { type: 'verse', ref: 'Ibrâhîm 14:7',
    ar: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
    de: '„Wenn ihr dankbar seid, so werde Ich euch wahrlich noch mehr geben.“',
    tr: '„Andolsun, eğer şükrederseniz elbette size (nimetimi) artırırım.“',
    en: '“If you are grateful, I will surely increase you [in favour].”' },

  tawakkul: { type: 'verse', ref: 'aṭ-Ṭalâq 65:3',
    ar: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
    de: '„Und wer sich auf Allah verlässt, dem ist Er seine Genüge.“',
    tr: '„Kim Allah’a tevekkül ederse, O ona yeter.“',
    en: '“And whoever relies upon Allah – then He is sufficient for him.”' },

  taqwa: { type: 'verse', ref: 'al-Ḥujurât 49:13',
    ar: 'إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ',
    de: '„Wahrlich, der Geehrteste von euch bei Allah ist der Gottesfürchtigste von euch.“',
    tr: '„Şüphesiz Allah katında en değerliniz, en çok takvâ sahibi olanınızdır.“',
    en: '“Indeed, the most noble of you in the sight of Allah is the most righteous of you.”' },

  prophet_mercy: { type: 'verse', ref: 'al-Anbiyâʾ 21:107',
    ar: 'وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِّلْعَالَمِينَ',
    de: '„Und Wir haben dich nur als Barmherzigkeit für die Weltenbewohner gesandt.“',
    tr: '„Seni ancak âlemlere rahmet olarak gönderdik.“',
    en: '“And We have not sent you except as a mercy to the worlds.”' },

  prophet_example: { type: 'verse', ref: 'al-Aḥzâb 33:21',
    ar: 'لَّقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ',
    de: '„Wahrlich, ihr habt im Gesandten Allahs ein schönes Vorbild.“',
    tr: '„Andolsun, Allah’ın Resûlü’nde sizin için güzel bir örnek vardır.“',
    en: '“There has certainly been for you in the Messenger of Allah an excellent example.”' },

  prophets_guided: { type: 'verse', ref: 'al-Anʿâm 6:90',
    ar: 'أُولَٰئِكَ الَّذِينَ هَدَى اللَّهُ ۖ فَبِهُدَاهُمُ اقْتَدِهْ',
    de: '„Das sind diejenigen, die Allah rechtgeleitet hat. So nimm ihre Rechtleitung zum Vorbild.“',
    tr: '„İşte onlar, Allah’ın hidayet ettiği kimselerdir. Sen de onların yoluna uy.“',
    en: '“Those are the ones whom Allah has guided, so follow their guidance.”' },

  ibrahim: { type: 'verse', ref: 'an-Naḥl 16:120',
    ar: 'إِنَّ إِبْرَاهِيمَ كَانَ أُمَّةً قَانِتًا لِّلَّهِ حَنِيفًا وَلَمْ يَكُ مِنَ الْمُشْرِكِينَ',
    de: '„Wahrlich, Ibrâhîm war ein Vorbild, Allah demütig ergeben, ein Ḥanîf, und er gehörte nicht zu den Götzendienern.“',
    tr: '„Şüphesiz İbrahim, Allah’a itaat eden, hakka yönelen (hanîf) bir önderdi; müşriklerden değildi.“',
    en: '“Indeed, Abraham was a nation, devoutly obedient to Allah, inclining toward truth, and he was not of the polytheists.”' },

  musa: { type: 'verse', ref: 'an-Nisâʾ 4:164',
    ar: 'وَكَلَّمَ اللَّهُ مُوسَىٰ تَكْلِيمًا',
    de: '„Und Allah sprach mit Mûsâ ein unmittelbares Sprechen.“',
    tr: '„Ve Allah, Mûsâ ile (vasıtasız) konuştu.“',
    en: '“And Allah spoke to Moses with [direct] speech.”' },

  isa: { type: 'verse', ref: 'Maryam 19:30',
    ar: 'قَالَ إِنِّي عَبْدُ اللَّهِ آتَانِيَ الْكِتَابَ وَجَعَلَنِي نَبِيًّا',
    de: '„Er sagte: Ich bin wahrlich Allahs Diener. Er hat mir die Schrift gegeben und mich zu einem Propheten gemacht.“',
    tr: '„(Îsâ) dedi ki: Şüphesiz ben Allah’ın kuluyum. Bana kitabı verdi ve beni peygamber yaptı.“',
    en: '“He said: Indeed, I am the servant of Allah. He has given me the Scripture and made me a prophet.”' },

  yusuf: { type: 'verse', ref: 'Yûsuf 12:90',
    ar: 'إِنَّهُ مَن يَتَّقِ وَيَصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ',
    de: '„Wer gottesfürchtig und geduldig ist – wahrlich, Allah lässt den Lohn der Gutes Tuenden nicht verlorengehen.“',
    tr: '„Kim Allah’tan korkar ve sabrederse, şüphesiz Allah iyilik edenlerin mükâfatını zayi etmez.“',
    en: '“Indeed, whoever is mindful of Allah and patient – Allah does not let the reward of those who do good be lost.”' },

  mecca_kaaba: { type: 'verse', ref: 'Âl ʿImrân 3:96',
    ar: 'إِنَّ أَوَّلَ بَيْتٍ وُضِعَ لِلنَّاسِ لَلَّذِي بِبَكَّةَ مُبَارَكًا وَهُدًى لِّلْعَالَمِينَ',
    de: '„Wahrlich, das erste Haus, das für die Menschen (zur Anbetung) errichtet wurde, ist das in Bakka (Mekka) – gesegnet und eine Rechtleitung für die Weltenbewohner.“',
    tr: '„Şüphesiz insanlar için kurulan ilk ev, Mekke’deki mübarek ve âlemlere hidayet olan (Kâbe)dir.“',
    en: '“Indeed, the first House established for mankind was that at Bakkah (Mecca) – blessed and a guidance for the worlds.”' },

  aqsa_isra: { type: 'verse', ref: 'al-Isrâʾ 17:1',
    ar: 'سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا مِّنَ الْمَسْجِدِ الْحَرَامِ إِلَى الْمَسْجِدِ الْأَقْصَى الَّذِي بَارَكْنَا حَوْلَهُ',
    de: '„Preis sei Dem, Der Seinen Diener bei Nacht vom heiligen Gebetshaus zum fernsten Gebetshaus (al-Aqsâ), dessen Umgebung Wir gesegnet haben, reisen ließ.“',
    tr: '„Kulunu bir gece Mescid-i Harâm’dan, çevresini bereketli kıldığımız Mescid-i Aksâ’ya götüren (Allah) her türlü noksanlıktan uzaktır.“',
    en: '“Exalted is He who took His servant by night from al-Masjid al-Ḥarâm to al-Masjid al-Aqṣâ, whose surroundings We have blessed.”' },

  dhikr: { type: 'verse', ref: 'ar-Raʿd 13:28',
    ar: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    de: '„Wahrlich, im Gedenken Allahs finden die Herzen Ruhe.“',
    tr: '„Bilin ki kalpler ancak Allah’ı anmakla huzur bulur.“',
    en: '“Unquestionably, by the remembrance of Allah hearts are assured.”' },

  quran_guidance: { type: 'verse', ref: 'al-Baqara 2:2',
    ar: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ',
    de: '„Dies ist das Buch, an dem es keinen Zweifel gibt, eine Rechtleitung für die Gottesfürchtigen.“',
    tr: '„Bu, kendisinde şüphe olmayan kitaptır; müttakiler için bir hidayettir.“',
    en: '“This is the Book about which there is no doubt, a guidance for those conscious of Allah.”' },

  fatiha: { type: 'verse', ref: 'al-Fâtiḥa 1:5',
    ar: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
    de: '„Dir allein dienen wir, und Dich allein bitten wir um Hilfe.“',
    tr: '„Yalnız sana kulluk eder, yalnız senden yardım dileriz.“',
    en: '“You alone we worship, and You alone we ask for help.”' },

  parents: { type: 'verse', ref: 'al-Isrâʾ 17:23',
    ar: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
    de: '„Und dein Herr hat bestimmt, dass ihr nur Ihm dient und zu den Eltern gütig seid.“',
    tr: '„Rabbin, yalnız kendisine ibadet etmenizi ve anne babaya iyilik etmenizi emretti.“',
    en: '“And your Lord has decreed that you worship none but Him, and to parents, good treatment.”' },

  iman_pillars: { type: 'verse', ref: 'al-Baqara 2:285',
    ar: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ',
    de: '„Der Gesandte glaubt an das, was zu ihm von seinem Herrn herabgesandt wurde, und (auch) die Gläubigen. Alle glauben an Allah, Seine Engel, Seine Bücher und Seine Gesandten.“',
    tr: '„Peygamber, Rabbinden kendisine indirilene iman etti, müminler de. Hepsi Allah’a, meleklerine, kitaplarına ve peygamberlerine iman etti.“',
    en: '“The Messenger believes in what was revealed to him from his Lord, and so do the believers. All believe in Allah, His angels, His books, and His messengers.”' },

  qiyama: { type: 'verse', ref: 'az-Zalzala 99:7–8',
    ar: 'فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ ۝ وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ',
    de: '„Wer auch nur ein Stäubchen Gutes tut, wird es sehen. Und wer auch nur ein Stäubchen Böses tut, wird es sehen.“',
    tr: '„Kim zerre kadar iyilik yaparsa onu görür; kim zerre kadar kötülük yaparsa onu görür.“',
    en: '“So whoever does an atom’s weight of good will see it, and whoever does an atom’s weight of evil will see it.”' },

  janna: { type: 'verse', ref: 'Âl ʿImrân 3:133',
    ar: 'وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ',
    de: '„Und wetteifert zu Vergebung von eurem Herrn und zu einem Paradiesgarten, dessen Breite (die) der Himmel und der Erde ist, bereitet für die Gottesfürchtigen.“',
    tr: '„Rabbinizin bağışına ve genişliği göklerle yer kadar olan, takva sahipleri için hazırlanmış cennete koşun.“',
    en: '“And hasten to forgiveness from your Lord and a Paradise as wide as the heavens and earth, prepared for the righteous.”' },

  badr: { type: 'verse', ref: 'Âl ʿImrân 3:123',
    ar: 'وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ وَأَنتُمْ أَذِلَّةٌ ۖ فَاتَّقُوا اللَّهَ لَعَلَّكُمْ تَشْكُرُونَ',
    de: '„Und Allah hat euch doch schon in Badr geholfen, als ihr schwach wart. So fürchtet Allah, auf dass ihr dankbar sein möget.“',
    tr: '„Andolsun, siz zayıf durumdayken Allah size Bedir’de yardım etti. Öyleyse Allah’tan sakının ki şükredesiniz.“',
    en: '“Allah had already helped you at Badr when you were weak. So fear Allah that you may be grateful.”' },

  victory: { type: 'verse', ref: 'an-Naṣr 110:1',
    ar: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ',
    de: '„Wenn Allahs Hilfe und der Sieg kommen.“',
    tr: '„Allah’ın yardımı ve fetih geldiğinde.“',
    en: '“When the help of Allah and the victory come.”' },

  laylatqadr: { type: 'verse', ref: 'al-Qadr 97:3',
    ar: 'لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ',
    de: '„Die Nacht der Bestimmung ist besser als tausend Monate.“',
    tr: '„Kadir gecesi bin aydan daha hayırlıdır.“',
    en: '“The Night of Decree is better than a thousand months.”' },

  ramadan: { type: 'verse', ref: 'al-Baqara 2:185',
    ar: 'شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ هُدًى لِّلنَّاسِ',
    de: '„Der Monat Ramadân, in dem der Qurʾân als Rechtleitung für die Menschen herabgesandt wurde.“',
    tr: '„Ramazan ayı, insanlar için hidayet olan Kur’an’ın indirildiği aydır.“',
    en: '“The month of Ramadan in which the Qurʾân was revealed as guidance for mankind.”' },

  quran_preserved: { type: 'verse', ref: 'al-Ḥijr 15:9',
    ar: 'إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',
    de: '„Gewiss, Wir sind es, die Wir die Ermahnung (den Qurʾân) offenbart haben, und Wir werden wahrlich über sie wachen.“',
    tr: '„Şüphesiz o zikri (Kur’an’ı) biz indirdik ve onu mutlaka biz koruyacağız.“',
    en: '“Indeed, it is We who sent down the Reminder, and indeed, We will be its guardian.”' },

  creation: { type: 'verse', ref: 'Âl ʿImrân 3:190',
    ar: 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ',
    de: '„Wahrlich, in der Schöpfung der Himmel und der Erde und im Wechsel von Nacht und Tag liegen Zeichen für die Einsichtigen.“',
    tr: '„Şüphesiz göklerin ve yerin yaratılışında, gece ile gündüzün ardarda gelişinde akıl sahipleri için âyetler vardır.“',
    en: '“Indeed, in the creation of the heavens and the earth and the alternation of night and day are signs for people of understanding.”' },

  provision: { type: 'verse', ref: 'al-Baqara 2:172',
    ar: 'كُلُوا مِن طَيِّبَاتِ مَا رَزَقْنَاكُمْ وَاشْكُرُوا لِلَّهِ',
    de: '„Esst von den guten Dingen, mit denen Wir euch versorgt haben, und seid Allah dankbar.“',
    tr: '„Size verdiğimiz rızıkların temiz olanlarından yiyin ve Allah’a şükredin.“',
    en: '“Eat from the good things We have provided you, and be grateful to Allah.”' },

  avoid_sin: { type: 'verse', ref: 'al-Anʿâm 6:151',
    ar: 'وَلَا تَقْرَبُوا الْفَوَاحِشَ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ',
    de: '„Und nähert euch nicht den Abscheulichkeiten, den offenkundigen von ihnen und den verborgenen.“',
    tr: '„Kötülüklerin açığına da gizlisine de yaklaşmayın.“',
    en: '“And do not approach immoralities — what is apparent of them and what is concealed.”' },

  /* --- Hadithe (nur Ṣaḥîḥ) --- */
  niyyah: { type: 'hadith', ref: 'Ṣaḥîḥ al-Bukhârî 1 · Ṣaḥîḥ Muslim 1907', grade: 'Ṣaḥîḥ',
    ar: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ',
    de: '„Die Taten werden nur nach den Absichten (bewertet).“',
    tr: '„Ameller ancak niyetlere göredir.“',
    en: '“Actions are but by intentions.”' },

  islam_pillars: { type: 'hadith', ref: 'Ṣaḥîḥ al-Bukhârî 8 · Ṣaḥîḥ Muslim 16', grade: 'Ṣaḥîḥ',
    ar: 'بُنِيَ الْإِسْلَامُ عَلَىٰ خَمْسٍ: شَهَادَةِ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلَاةِ، وَإِيتَاءِ الزَّكَاةِ، وَحَجِّ الْبَيْتِ، وَصَوْمِ رَمَضَانَ',
    de: '„Der Islam ist auf fünf (Säulen) errichtet: das Zeugnis, dass es keinen Gott außer Allah gibt und dass Muhammad der Gesandte Allahs ist; das Gebet; die Zakât; die Pilgerfahrt zum Haus; und das Fasten im Ramadân.“',
    tr: '„İslam beş temel üzerine kurulmuştur: Allah’tan başka ilah olmadığına ve Muhammed’in O’nun elçisi olduğuna şehadet, namaz, zekât, hac ve Ramazan orucu.“',
    en: '“Islam is built upon five: to testify that there is no god but Allah and that Muhammad is His Messenger, to establish prayer, to give zakah, to make the pilgrimage, and to fast Ramadan.”' },

  purity: { type: 'hadith', ref: 'Ṣaḥîḥ Muslim 223', grade: 'Ṣaḥîḥ',
    ar: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
    de: '„Die Reinheit ist die Hälfte des Glaubens.“',
    tr: '„Temizlik imanın yarısıdır.“',
    en: '“Purity is half of faith.”' },

  love_brother: { type: 'hadith', ref: 'Ṣaḥîḥ al-Bukhârî 13 · Ṣaḥîḥ Muslim 45', grade: 'Ṣaḥîḥ',
    ar: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّىٰ يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    de: '„Keiner von euch glaubt (vollkommen), bis er für seinen Bruder liebt, was er für sich selbst liebt.“',
    tr: '„Sizden biri, kendisi için istediğini kardeşi için de istemedikçe (kâmil manada) iman etmiş olmaz.“',
    en: '“None of you truly believes until he loves for his brother what he loves for himself.”' },

  good_word: { type: 'hadith', ref: 'Ṣaḥîḥ al-Bukhârî 6018 · Ṣaḥîḥ Muslim 47', grade: 'Ṣaḥîḥ',
    ar: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    de: '„Wer an Allah und den Jüngsten Tag glaubt, der soll Gutes sagen oder schweigen.“',
    tr: '„Allah’a ve ahiret gününe iman eden ya hayır söylesin ya da sussun.“',
    en: '“Whoever believes in Allah and the Last Day, let him speak good or remain silent.”' },

  muslim_safe: { type: 'hadith', ref: 'Ṣaḥîḥ al-Bukhârî 10 · Ṣaḥîḥ Muslim 40', grade: 'Ṣaḥîḥ',
    ar: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
    de: '„Der Muslim ist derjenige, vor dessen Zunge und Hand die (anderen) Muslime sicher sind.“',
    tr: '„Müslüman, diğer Müslümanların dilinden ve elinden emin olduğu kimsedir.“',
    en: '“The Muslim is the one from whose tongue and hand the Muslims are safe.”' },

  salawat: { type: 'hadith', ref: 'Ṣaḥîḥ Muslim 384', grade: 'Ṣaḥîḥ',
    ar: 'مَنْ صَلَّىٰ عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا',
    de: '„Wer ein einziges Mal den Segensgruß über mich spricht, über den spricht Allah dafür zehnfachen Segen.“',
    tr: '„Kim bana bir defa salât (salavat) getirirse, Allah ona bununla on kere rahmet eder.“',
    en: '“Whoever sends one blessing upon me, Allah sends ten blessings upon him for it.”' },

  nasiha_deen: { type: 'hadith', ref: 'Ṣaḥîḥ Muslim 55', grade: 'Ṣaḥîḥ',
    ar: 'الدِّينُ النَّصِيحَةُ',
    de: '„Die Religion ist der aufrichtige Rat (Naṣîḥa).“',
    tr: '„Din nasihattir (samimiyet ve iyilik dilemektir).“',
    en: '“The religion is sincere advice (Naṣîḥa).”' },
};

const CATEGORY_DEFAULT_NASIHA = {
  prophets: 'prophets_guided', companions: 'love_brother', worship: 'worship_purpose',
  quran: 'quran_guidance', places: 'mecca_kaaba', akhlaq: 'taqwa',
  aqida: 'iman_pillars', history: 'victory',
  objects: 'creation', animals: 'creation', food: 'provision', jobs: 'muslim_safe',
  people: 'love_brother', good_deeds: 'love_brother', bad_deeds: 'avoid_sin',
};
const DEFAULT_NASIHA = 'nasiha_deen';

/* ---------- Begriffe ----------
   level: 1=Leicht · 2=Mittel · 3=Schwer · 4=Sehr schwer
   w = Wort · h = Hinweiswort (für den Gharîb auf „Leicht“) · n = Nasîha-Schlüssel
*/
const TERMS = [
  /* ===== Propheten ===== */
  { cat:'prophets', level:1, n:'prophets_guided', w:{de:'Âdam',tr:'Âdem',en:'Âdam',ar:'آدم'}, h:{de:'erster Mensch',tr:'ilk insan',en:'first human',ar:'أول إنسان'} },
  { cat:'prophets', level:1, n:'ibrahim', w:{de:'Ibrâhîm',tr:'İbrahim',en:'Ibrâhîm',ar:'إبراهيم'}, h:{de:'Freund Allahs',tr:'Halîlullah',en:'Friend of Allah',ar:'الخليل'} },
  { cat:'prophets', level:1, n:'musa', w:{de:'Mûsâ',tr:'Mûsâ',en:'Mûsâ',ar:'موسى'}, h:{de:'der Stab',tr:'asa',en:'the staff',ar:'العصا'} },
  { cat:'prophets', level:1, n:'isa', w:{de:'ʿÎsâ',tr:'Îsâ',en:'ʿÎsâ',ar:'عيسى'}, h:{de:'Sohn Maryams',tr:'Meryem oğlu',en:'son of Mary',ar:'ابن مريم'} },
  { cat:'prophets', level:1, n:'prophet_mercy', w:{de:'Muḥammad ﷺ',tr:'Muhammed ﷺ',en:'Muḥammad ﷺ',ar:'محمد ﷺ'}, h:{de:'Siegel der Propheten',tr:'son peygamber',en:'final prophet',ar:'خاتم الأنبياء'} },
  { cat:'prophets', level:2, n:'prophets_guided', w:{de:'Nûḥ',tr:'Nûh',en:'Nûḥ',ar:'نوح'}, h:{de:'die Arche',tr:'gemi',en:'the ark',ar:'السفينة'} },
  { cat:'prophets', level:2, n:'yusuf', w:{de:'Yûsuf',tr:'Yûsuf',en:'Yûsuf',ar:'يوسف'}, h:{de:'der Brunnen',tr:'kuyu',en:'the well',ar:'البئر'} },
  { cat:'prophets', level:3, n:'prophets_guided', w:{de:'Sulaymân',tr:'Süleyman',en:'Sulaymân',ar:'سليمان'}, h:{de:'das Königreich',tr:'hükümdarlık',en:'the kingdom',ar:'المُلك'} },
  { cat:'prophets', level:3, n:'ease', w:{de:'Yûnus',tr:'Yûnus',en:'Yûnus',ar:'يونس'}, h:{de:'der große Fisch',tr:'balık',en:'the whale',ar:'الحوت'} },
  { cat:'prophets', level:3, n:'prophets_guided', w:{de:'Dâwûd',tr:'Dâvûd',en:'Dâwûd',ar:'داود'}, h:{de:'der Zabûr',tr:'Zebûr',en:'the Psalms',ar:'الزبور'} },
  { cat:'prophets', level:3, n:'ibrahim', w:{de:'Ismâʿîl',tr:'İsmail',en:'Ismâʿîl',ar:'إسماعيل'}, h:{de:'das Opfer',tr:'kurban',en:'the sacrifice',ar:'الذبح'} },
  { cat:'prophets', level:4, n:'prophets_guided', w:{de:'Zakariyyâ',tr:'Zekeriyyâ',en:'Zakariyyâ',ar:'زكريا'}, h:{de:'das Bittgebet',tr:'dua',en:'supplication',ar:'الدعاء'} },

  /* ===== Gefährten (Ṣaḥâba) ===== */
  { cat:'companions', level:1, n:'love_brother', w:{de:'Abû Bakr aṣ-Ṣiddîq',tr:'Ebû Bekir',en:'Abû Bakr',ar:'أبو بكر الصدّيق'}, h:{de:'erster Kalif',tr:'ilk halife',en:'first caliph',ar:'أول خليفة'} },
  { cat:'companions', level:1, n:'taqwa', w:{de:'ʿUmar al-Fârûq',tr:'Ömer',en:'ʿUmar',ar:'عمر بن الخطاب'}, h:{de:'die Gerechtigkeit',tr:'adalet',en:'justice',ar:'العدل'} },
  { cat:'companions', level:1, n:'knowledge', w:{de:'ʿAlî ibn Abî Ṭâlib',tr:'Ali',en:'ʿAlî',ar:'علي بن أبي طالب'}, h:{de:'Tor des Wissens',tr:'ilim kapısı',en:'gate of knowledge',ar:'باب العلم'} },
  { cat:'companions', level:2, n:'good_word', w:{de:'ʿUthmân ibn ʿAffân',tr:'Osman',en:'ʿUthmân',ar:'عثمان بن عفّان'}, h:{de:'der mit den zwei Lichtern',tr:'Zinnûreyn',en:'the two lights',ar:'ذو النورين'} },
  { cat:'companions', level:2, n:'salah', w:{de:'Bilâl al-Ḥabashî',tr:'Bilâl-i Habeşî',en:'Bilâl',ar:'بلال الحبشي'}, h:{de:'der erste Muezzin',tr:'ilk müezzin',en:'first muezzin',ar:'أول مؤذّن'} },
  { cat:'companions', level:2, n:'sabr', w:{de:'Khadîja',tr:'Hatice',en:'Khadîja',ar:'خديجة'}, h:{de:'erste Gläubige',tr:'ilk iman eden',en:'first believer',ar:'أول مؤمنة'} },
  { cat:'companions', level:2, n:'knowledge', w:{de:'ʿÂʾisha',tr:'Âişe',en:'ʿÂʾisha',ar:'عائشة'}, h:{de:'die Gelehrte',tr:'âlime',en:'the scholar',ar:'العالِمة'} },
  { cat:'companions', level:3, n:'tawakkul', w:{de:'Khâlid ibn al-Walîd',tr:'Hâlid bin Velîd',en:'Khâlid ibn al-Walîd',ar:'خالد بن الوليد'}, h:{de:'Schwert Allahs',tr:'Allah’ın kılıcı',en:'Sword of Allah',ar:'سيف الله'} },
  { cat:'companions', level:3, n:'prophet_example', w:{de:'Fâṭima az-Zahrâʾ',tr:'Fâtıma',en:'Fâṭima',ar:'فاطمة الزهراء'}, h:{de:'Tochter des Propheten ﷺ',tr:'Peygamber’in kızı',en:'the Prophet’s daughter',ar:'بنت النبي ﷺ'} },
  { cat:'companions', level:4, n:'tawakkul', w:{de:'Ḥamza',tr:'Hamza',en:'Ḥamza',ar:'حمزة'}, h:{de:'Löwe Allahs',tr:'Allah’ın aslanı',en:'Lion of Allah',ar:'أسد الله'} },
  { cat:'companions', level:4, n:'knowledge', w:{de:'Salmân al-Fârisî',tr:'Selmân-ı Fârisî',en:'Salmân al-Fârisî',ar:'سلمان الفارسي'}, h:{de:'der Perser',tr:'Farslı',en:'the Persian',ar:'الفارسي'} },
  { cat:'companions', level:4, n:'prophets_guided', w:{de:'Muṣʿab ibn ʿUmayr',tr:'Musʿab bin Umeyr',en:'Muṣʿab ibn ʿUmayr',ar:'مصعب بن عمير'}, h:{de:'erster Gesandter',tr:'ilk davetçi',en:'first envoy',ar:'أول سفير'} },

  /* ===== Gottesdienst (ʿIbâda) ===== */
  { cat:'worship', level:1, n:'salah', w:{de:'Ṣalâh (Gebet)',tr:'Namaz',en:'Ṣalâh (Prayer)',ar:'الصلاة'}, h:{de:'fünfmal am Tag',tr:'beş vakit',en:'five times a day',ar:'خمس مرات'} },
  { cat:'worship', level:1, n:'zakat_salah', w:{de:'Zakât',tr:'Zekât',en:'Zakât',ar:'الزكاة'}, h:{de:'Pflichtabgabe',tr:'sadaka',en:'obligatory charity',ar:'الصدقة'} },
  { cat:'worship', level:1, n:'sawm', w:{de:'Ṣawm (Fasten)',tr:'Oruç',en:'Ṣawm (Fasting)',ar:'الصوم'}, h:{de:'Ramadân',tr:'Ramazan',en:'Ramadan',ar:'رمضان'} },
  { cat:'worship', level:1, n:'hajj', w:{de:'Ḥajj',tr:'Hac',en:'Ḥajj',ar:'الحج'}, h:{de:'Reise nach Mekka',tr:'Mekke yolculuğu',en:'journey to Mecca',ar:'مكة'} },
  { cat:'worship', level:1, n:'islam_pillars', w:{de:'Shahâda',tr:'Şehadet',en:'Shahâda',ar:'الشهادة'}, h:{de:'das Bekenntnis',tr:'kelime-i şehadet',en:'the testimony',ar:'لا إله إلا الله'} },
  { cat:'worship', level:2, n:'purity', w:{de:'Wuḍûʾ',tr:'Abdest',en:'Wuḍûʾ',ar:'الوضوء'}, h:{de:'Reinheit',tr:'temizlik',en:'purity',ar:'الطهارة'} },
  { cat:'worship', level:2, n:'dhikr', w:{de:'Duʿâʾ',tr:'Dua',en:'Duʿâʾ',ar:'الدعاء'}, h:{de:'Bittgebet',tr:'yakarış',en:'supplication',ar:'الطلب'} },
  { cat:'worship', level:2, n:'dhikr', w:{de:'Dhikr',tr:'Zikir',en:'Dhikr',ar:'الذكر'}, h:{de:'Gedenken Allahs',tr:'Allah’ı anmak',en:'remembrance',ar:'التسبيح'} },
  { cat:'worship', level:2, n:'salah', w:{de:'Adhân',tr:'Ezan',en:'Adhân',ar:'الأذان'}, h:{de:'Gebetsruf',tr:'namaza çağrı',en:'call to prayer',ar:'النداء'} },
  { cat:'worship', level:2, n:'tawhid', w:{de:'Tawḥîd',tr:'Tevhid',en:'Tawḥîd',ar:'التوحيد'}, h:{de:'Einheit Allahs',tr:'Allah’ın birliği',en:'Oneness of Allah',ar:'الوحدانية'} },
  { cat:'worship', level:2, n:'worship_purpose', w:{de:'Îmân',tr:'İman',en:'Îmân',ar:'الإيمان'}, h:{de:'der Glaube',tr:'inanç',en:'faith',ar:'التصديق'} },
  { cat:'worship', level:3, n:'zakat_salah', w:{de:'Ṣadaqa',tr:'Sadaka',en:'Ṣadaqa',ar:'الصدقة'}, h:{de:'freiwillige Gabe',tr:'gönüllü yardım',en:'voluntary giving',ar:'التطوع'} },
  { cat:'worship', level:4, n:'purity', w:{de:'Tayammum',tr:'Teyemmüm',en:'Tayammum',ar:'التيمم'}, h:{de:'Reinigung mit Erde',tr:'toprakla temizlik',en:'dry ablution',ar:'بالتراب'} },
  { cat:'worship', level:4, n:'dhikr', w:{de:'Iʿtikâf',tr:'İtikâf',en:'Iʿtikâf',ar:'الاعتكاف'}, h:{de:'Rückzug in die Moschee',tr:'mescitte inziva',en:'seclusion in the mosque',ar:'في المسجد'} },

  /* ===== Qurʾân & Suren ===== */
  { cat:'quran', level:1, n:'fatiha', w:{de:'al-Fâtiḥa',tr:'Fâtiha',en:'al-Fâtiḥa',ar:'الفاتحة'}, h:{de:'die Eröffnende',tr:'açılış suresi',en:'the Opening',ar:'أم الكتاب'} },
  { cat:'quran', level:1, n:'tawhid', w:{de:'al-Ikhlâṣ',tr:'İhlâs',en:'al-Ikhlâṣ',ar:'الإخلاص'}, h:{de:'Tawḥîd-Sure',tr:'tevhid suresi',en:'surah of Tawhîd',ar:'قل هو الله أحد'} },
  { cat:'quran', level:2, n:'tawhid', w:{de:'Âyat al-Kursî',tr:'Âyetü’l-Kürsî',en:'Âyat al-Kursî',ar:'آية الكرسي'}, h:{de:'der Thronvers',tr:'en büyük ayet',en:'the Throne Verse',ar:'أعظم آية'} },
  { cat:'quran', level:2, n:'quran_guidance', w:{de:'Yâ Sîn',tr:'Yâsîn',en:'Yâ Sîn',ar:'يس'}, h:{de:'Herz des Qurʾân',tr:'Kurʾân’ın kalbi',en:'heart of the Qurʾân',ar:'قلب القرآن'} },
  { cat:'quran', level:2, n:'quran_guidance', w:{de:'al-Baqara',tr:'Bakara',en:'al-Baqara',ar:'البقرة'}, h:{de:'längste Sure',tr:'en uzun sure',en:'longest surah',ar:'أطول سورة'} },
  { cat:'quran', level:2, n:'tawhid', w:{de:'an-Nâs',tr:'Nâs',en:'an-Nâs',ar:'الناس'}, h:{de:'letzte Sure',tr:'son sure',en:'last surah',ar:'آخر سورة'} },
  { cat:'quran', level:3, n:'salah', w:{de:'al-Kawthar',tr:'Kevser',en:'al-Kawthar',ar:'الكوثر'}, h:{de:'kürzeste Sure',tr:'en kısa sure',en:'shortest surah',ar:'أقصر سورة'} },
  { cat:'quran', level:3, n:'quran_guidance', w:{de:'al-Mulk',tr:'Mülk',en:'al-Mulk',ar:'الملك'}, h:{de:'die Beschützerin',tr:'koruyan sure',en:'the protector',ar:'تبارك'} },
  { cat:'quran', level:3, n:'quran_guidance', w:{de:'al-Kahf',tr:'Kehf',en:'al-Kahf',ar:'الكهف'}, h:{de:'Freitagssure',tr:'Cuma suresi',en:'Friday surah',ar:'أصحاب الكهف'} },
  { cat:'quran', level:3, n:'tawhid', w:{de:'al-Falaq',tr:'Felak',en:'al-Falaq',ar:'الفلق'}, h:{de:'das Tagesgrauen',tr:'şafak',en:'the daybreak',ar:'الصبح'} },
  { cat:'quran', level:4, n:'tawhid', w:{de:'al-Muʿawwidhatân',tr:'Muavvizeteyn',en:'al-Muʿawwidhatân',ar:'المعوذتان'}, h:{de:'die zwei Schutzsuren',tr:'iki koruyucu sure',en:'the two refuge surahs',ar:'الفلق والناس'} },
  { cat:'quran', level:4, n:'first_revelation', w:{de:'al-ʿAlaq',tr:'Alak',en:'al-ʿAlaq',ar:'العلق'}, h:{de:'erste Offenbarung',tr:'ilk vahiy',en:'first revelation',ar:'أول ما نزل'} },

  /* ===== Heilige Orte ===== */
  { cat:'places', level:1, n:'mecca_kaaba', w:{de:'al-Kaʿba',tr:'Kâbe',en:'al-Kaʿba',ar:'الكعبة'}, h:{de:'die Qibla',tr:'kıble',en:'the qibla',ar:'القبلة'} },
  { cat:'places', level:1, n:'mecca_kaaba', w:{de:'Makka (Mekka)',tr:'Mekke',en:'Makkah',ar:'مكة'}, h:{de:'Mutter der Städte',tr:'şehirlerin anası',en:'mother of cities',ar:'أم القرى'} },
  { cat:'places', level:1, n:'salawat', w:{de:'al-Madîna',tr:'Medine',en:'al-Madînah',ar:'المدينة'}, h:{de:'Stadt des Propheten ﷺ',tr:'Peygamber şehri',en:'city of the Prophet ﷺ',ar:'طيبة'} },
  { cat:'places', level:2, n:'aqsa_isra', w:{de:'al-Masjid al-Aqṣâ',tr:'Mescid-i Aksâ',en:'al-Masjid al-Aqṣâ',ar:'المسجد الأقصى'}, h:{de:'die erste Qibla',tr:'ilk kıble',en:'the first qibla',ar:'أولى القبلتين'} },
  { cat:'places', level:2, n:'mecca_kaaba', w:{de:'Zamzam',tr:'Zemzem',en:'Zamzam',ar:'زمزم'}, h:{de:'gesegnetes Wasser',tr:'mübarek su',en:'blessed water',ar:'ماء مبارك'} },
  { cat:'places', level:2, n:'salawat', w:{de:'al-Masjid an-Nabawî',tr:'Mescid-i Nebevî',en:'al-Masjid an-Nabawî',ar:'المسجد النبوي'}, h:{de:'Moschee des Propheten ﷺ',tr:'Peygamber mescidi',en:'the Prophet’s Mosque ﷺ',ar:'الروضة'} },
  { cat:'places', level:3, n:'hajj', w:{de:'ʿArafât',tr:'Arafat',en:'ʿArafât',ar:'عرفات'}, h:{de:'Tag des Ḥajj',tr:'vakfe',en:'the standing',ar:'الوقوف'} },
  { cat:'places', level:3, n:'hajj', w:{de:'aṣ-Ṣafâ wa-l-Marwa',tr:'Safâ ve Merve',en:'aṣ-Ṣafâ & al-Marwa',ar:'الصفا والمروة'}, h:{de:'der Saʿy',tr:'sa’y',en:'the walk (Saʿy)',ar:'السعي'} },
  { cat:'places', level:3, n:'tawakkul', w:{de:'Uḥud',tr:'Uhud',en:'Uḥud',ar:'أحد'}, h:{de:'der Berg',tr:'dağ',en:'the mountain',ar:'الجبل'} },
  { cat:'places', level:4, n:'first_revelation', w:{de:'Ḥirâʾ',tr:'Hira',en:'Ḥirâʾ',ar:'حراء'}, h:{de:'Höhle der Offenbarung',tr:'vahiy mağarası',en:'cave of revelation',ar:'الغار'} },
  { cat:'places', level:4, n:'hajj', w:{de:'Minâ',tr:'Mina',en:'Minâ',ar:'منى'}, h:{de:'die Zelte',tr:'çadırlar',en:'the tents',ar:'الجمرات'} },
  { cat:'places', level:4, n:'mecca_kaaba', w:{de:'al-Ḥaramayn',tr:'Harameyn',en:'al-Ḥaramayn',ar:'الحرمين'}, h:{de:'die zwei heiligen Stätten',tr:'iki harem',en:'the two sanctuaries',ar:'مكة والمدينة'} },

  /* ===== Charakter (Akhlâq) ===== */
  { cat:'akhlaq', level:1, n:'sabr', w:{de:'Ṣabr (Geduld)',tr:'Sabır',en:'Ṣabr (Patience)',ar:'الصبر'}, h:{de:'Standhaftigkeit',tr:'metanet',en:'steadfastness',ar:'التحمل'} },
  { cat:'akhlaq', level:1, n:'shukr', w:{de:'Shukr (Dankbarkeit)',tr:'Şükür',en:'Shukr (Gratitude)',ar:'الشكر'}, h:{de:'Danken',tr:'teşekkür',en:'thankfulness',ar:'الحمد'} },
  { cat:'akhlaq', level:1, n:'prophet_mercy', w:{de:'Raḥma (Barmherzigkeit)',tr:'Merhamet',en:'Raḥma (Mercy)',ar:'الرحمة'}, h:{de:'Mitgefühl',tr:'şefkat',en:'compassion',ar:'العطف'} },
  { cat:'akhlaq', level:2, n:'niyyah', w:{de:'Ikhlâṣ (Aufrichtigkeit)',tr:'İhlâs',en:'Ikhlâṣ (Sincerity)',ar:'الإخلاص'}, h:{de:'reine Absicht',tr:'samimiyet',en:'pure intention',ar:'النية'} },
  { cat:'akhlaq', level:2, n:'tawakkul', w:{de:'Tawakkul',tr:'Tevekkül',en:'Tawakkul',ar:'التوكل'}, h:{de:'Gottvertrauen',tr:'Allah’a güven',en:'reliance on Allah',ar:'الاعتماد على الله'} },
  { cat:'akhlaq', level:2, n:'good_word', w:{de:'Ṣidq (Wahrhaftigkeit)',tr:'Sıdk (Doğruluk)',en:'Ṣidq (Truthfulness)',ar:'الصدق'}, h:{de:'Ehrlichkeit',tr:'dürüstlük',en:'honesty',ar:'الصراحة'} },
  { cat:'akhlaq', level:2, n:'muslim_safe', w:{de:'Amâna',tr:'Emanet',en:'Amâna',ar:'الأمانة'}, h:{de:'Vertrauenswürdigkeit',tr:'güvenilirlik',en:'trustworthiness',ar:'الوفاء'} },
  { cat:'akhlaq', level:2, n:'taqwa', w:{de:'Taqwâ',tr:'Takvâ',en:'Taqwâ',ar:'التقوى'}, h:{de:'Gottesfurcht',tr:'Allah bilinci',en:'God-consciousness',ar:'الخوف من الله'} },
  { cat:'akhlaq', level:3, n:'parents', w:{de:'Birr al-Wâlidayn',tr:'Ana-babaya iyilik',en:'Birr al-Wâlidayn',ar:'بر الوالدين'}, h:{de:'Güte zu den Eltern',tr:'anne-babaya iyilik',en:'kindness to parents',ar:'الإحسان للوالدين'} },
  { cat:'akhlaq', level:3, n:'taqwa', w:{de:'Tawâḍuʿ (Demut)',tr:'Tevazu',en:'Tawâḍuʿ (Humility)',ar:'التواضع'}, h:{de:'Bescheidenheit',tr:'alçakgönüllülük',en:'modesty',ar:'التذلل'} },
  { cat:'akhlaq', level:3, n:'good_word', w:{de:'ʿAfw (Vergebung)',tr:'Af',en:'ʿAfw (Forgiveness)',ar:'العفو'}, h:{de:'Verzeihen',tr:'bağışlamak',en:'pardon',ar:'المغفرة'} },
  { cat:'akhlaq', level:3, n:'love_brother', w:{de:'Ḥayâʾ (Schamgefühl)',tr:'Hayâ',en:'Ḥayâʾ (Modesty)',ar:'الحياء'}, h:{de:'Ehrgefühl vor Allah',tr:'edep',en:'bashfulness',ar:'الحشمة'} },
  { cat:'akhlaq', level:4, n:'good_word', w:{de:'Ḥilm (Sanftmut)',tr:'Hilm (Yumuşaklık)',en:'Ḥilm (Forbearance)',ar:'الحلم'}, h:{de:'Geduld im Zorn',tr:'öfkeye hâkimiyet',en:'calm in anger',ar:'ضبط النفس'} },
  { cat:'akhlaq', level:4, n:'love_brother', w:{de:'Ṣilat ar-Raḥim',tr:'Sıla-i Rahim',en:'Ṣilat ar-Raḥim',ar:'صلة الرحم'}, h:{de:'Verwandtschaftspflege',tr:'akraba ziyareti',en:'kinship ties',ar:'القرابة'} },

  /* ===== Propheten (weitere) ===== */
  { cat:'prophets', level:3, n:'prophets_guided', w:{de:'Hârûn',tr:'Hârûn',en:'Hârûn',ar:'هارون'}, h:{de:'Bruder von Mûsâ',tr:'Mûsâ’nın kardeşi',en:'brother of Mûsâ',ar:'أخو موسى'} },
  { cat:'prophets', level:3, n:'sabr', w:{de:'Ayyûb',tr:'Eyyûb',en:'Ayyûb',ar:'أيوب'}, h:{de:'Geduld in Krankheit',tr:'hastalıkta sabır',en:'patience in illness',ar:'الصبر في المرض'} },
  { cat:'prophets', level:3, n:'yusuf', w:{de:'Yaʿqûb',tr:'Yâkûb',en:'Yaʿqûb',ar:'يعقوب'}, h:{de:'Vater von Yûsuf',tr:'Yûsuf’un babası',en:'father of Yûsuf',ar:'أبو يوسف'} },
  { cat:'prophets', level:3, n:'prophets_guided', w:{de:'Yaḥyâ',tr:'Yahyâ',en:'Yaḥyâ',ar:'يحيى'}, h:{de:'Sohn von Zakariyyâ',tr:'Zekeriyyâ’nın oğlu',en:'son of Zakariyyâ',ar:'ابن زكريا'} },
  { cat:'prophets', level:3, n:'prophets_guided', w:{de:'Lûṭ',tr:'Lût',en:'Lûṭ',ar:'لوط'}, h:{de:'sein Volk',tr:'kavmi',en:'his people',ar:'قومه'} },
  { cat:'prophets', level:4, n:'prophets_guided', w:{de:'Idrîs',tr:'İdrîs',en:'Idrîs',ar:'إدريس'}, h:{de:'hoch erhoben',tr:'yüce makam',en:'raised high',ar:'مكانًا عليًّا'} },
  { cat:'prophets', level:4, n:'prophets_guided', w:{de:'Hûd',tr:'Hûd',en:'Hûd',ar:'هود'}, h:{de:'Volk ʿÂd',tr:'Âd kavmi',en:'people of ʿÂd',ar:'عاد'} },
  { cat:'prophets', level:4, n:'prophets_guided', w:{de:'Ṣâliḥ',tr:'Sâlih',en:'Ṣâliḥ',ar:'صالح'}, h:{de:'die Kamelstute',tr:'deve mucizesi',en:'the she-camel',ar:'الناقة'} },
  { cat:'prophets', level:4, n:'prophets_guided', w:{de:'Shuʿayb',tr:'Şuayb',en:'Shuʿayb',ar:'شعيب'}, h:{de:'Volk von Madyan',tr:'Medyen halkı',en:'people of Madyan',ar:'مدين'} },

  /* ===== Gefährten (weitere) ===== */
  { cat:'companions', level:2, n:'knowledge', w:{de:'Abû Hurayra',tr:'Ebû Hüreyre',en:'Abû Hurayra',ar:'أبو هريرة'}, h:{de:'überlieferte viele Hadithe',tr:'çok hadis rivayet etti',en:'narrated many hadiths',ar:'كثير الحديث'} },
  { cat:'companions', level:3, n:'knowledge', w:{de:'Ibn ʿAbbâs',tr:'İbn Abbâs',en:'Ibn ʿAbbâs',ar:'ابن عباس'}, h:{de:'Gelehrter der Umma',tr:'ümmetin âlimi',en:'scholar of the Ummah',ar:'حبر الأمة'} },
  { cat:'companions', level:4, n:'knowledge', w:{de:'Muʿâdh ibn Jabal',tr:'Muâz bin Cebel',en:'Muʿâdh ibn Jabal',ar:'معاذ بن جبل'}, h:{de:'kannte Ḥalâl & Ḥarâm',tr:'helal-haram bilgini',en:'knew halâl & harâm',ar:'أعلمهم بالحلال والحرام'} },
  { cat:'companions', level:4, n:'prophet_example', w:{de:'Zayd ibn Ḥâritha',tr:'Zeyd bin Hârise',en:'Zayd ibn Ḥâritha',ar:'زيد بن حارثة'}, h:{de:'der Geliebte',tr:'sevgili sahâbî',en:'the beloved',ar:'الحِبّ'} },
  { cat:'companions', level:4, n:'tawakkul', w:{de:'Saʿd ibn Abî Waqqâṣ',tr:'Sa’d bin Ebî Vakkâs',en:'Saʿd ibn Abî Waqqâṣ',ar:'سعد بن أبي وقاص'}, h:{de:'erhörtes Bittgebet',tr:'duası makbul',en:'answered supplication',ar:'مستجاب الدعوة'} },
  { cat:'companions', level:4, n:'tawakkul', w:{de:'az-Zubayr ibn al-ʿAwwâm',tr:'Zübeyr bin Avvâm',en:'az-Zubayr ibn al-ʿAwwâm',ar:'الزبير بن العوام'}, h:{de:'Jünger des Propheten ﷺ',tr:'havârî',en:'disciple of the Prophet ﷺ',ar:'حواري النبي ﷺ'} },
  { cat:'companions', level:4, n:'zakat_salah', w:{de:'ʿAbd ar-Raḥmân ibn ʿAwf',tr:'Abdurrahman bin Avf',en:'ʿAbd ar-Raḥmân ibn ʿAwf',ar:'عبد الرحمن بن عوف'}, h:{de:'freigebiger Händler',tr:'cömert tüccar',en:'generous merchant',ar:'التاجر الكريم'} },
  { cat:'companions', level:3, n:'prophet_example', w:{de:'Anas ibn Mâlik',tr:'Enes bin Mâlik',en:'Anas ibn Mâlik',ar:'أنس بن مالك'}, h:{de:'Diener des Propheten ﷺ',tr:'Peygamber’in hizmetçisi',en:'servant of the Prophet ﷺ',ar:'خادم النبي ﷺ'} },

  /* ===== Gottesdienst (weitere) ===== */
  { cat:'worship', level:2, n:'salah', w:{de:'Sujûd',tr:'Secde',en:'Sujûd',ar:'السجود'}, h:{de:'Stirn auf dem Boden',tr:'alnı yere koymak',en:'prostration',ar:'وضع الجبهة'} },
  { cat:'worship', level:2, n:'mecca_kaaba', w:{de:'Qibla',tr:'Kıble',en:'Qibla',ar:'القبلة'}, h:{de:'Richtung zur Kaʿba',tr:'Kâbe yönü',en:'direction of prayer',ar:'اتجاه الكعبة'} },
  { cat:'worship', level:3, n:'dhikr', w:{de:'Tasbîḥ',tr:'Tesbih',en:'Tasbîḥ',ar:'التسبيح'}, h:{de:'SubḥânAllâh',tr:'Sübhânallah',en:'SubḥânAllâh',ar:'سبحان الله'} },
  { cat:'worship', level:2, n:'dhikr', w:{de:'Istighfâr',tr:'İstiğfar',en:'Istighfâr',ar:'الاستغفار'}, h:{de:'um Vergebung bitten',tr:'af dilemek',en:'seeking forgiveness',ar:'أستغفر الله'} },
  { cat:'worship', level:2, n:'sawm', w:{de:'Tarâwîḥ',tr:'Teravih',en:'Tarâwîḥ',ar:'التراويح'}, h:{de:'Ramadân-Nachtgebet',tr:'Ramazan gece namazı',en:'Ramadan night prayer',ar:'قيام رمضان'} },
  { cat:'worship', level:3, n:'salah', w:{de:'Tahajjud',tr:'Teheccüd',en:'Tahajjud',ar:'التهجد'}, h:{de:'Gebet in der Nacht',tr:'gece namazı',en:'night prayer',ar:'قيام الليل'} },
  { cat:'worship', level:3, n:'salah', w:{de:'Witr',tr:'Vitir',en:'Witr',ar:'الوتر'}, h:{de:'ungerade Rakʿa',tr:'tek rekât',en:'odd prayer',ar:'ركعة فردية'} },
  { cat:'worship', level:3, n:'zakat_salah', w:{de:'Ṣadaqa Jâriya',tr:'Sadaka-i Câriye',en:'Ṣadaqa Jâriya',ar:'صدقة جارية'}, h:{de:'fortlaufende Wohltat',tr:'süregelen sadaka',en:'ongoing charity',ar:'الصدقة المستمرة'} },

  /* ===== Qurʾân & Suren (weitere) ===== */
  { cat:'quran', level:3, n:'shukr', w:{de:'ar-Raḥmân',tr:'Rahmân',en:'ar-Raḥmân',ar:'الرحمن'}, h:{de:'„welche Wohltat …?“',tr:'hangi nimet',en:'“which favours…?”',ar:'فبأي آلاء'} },
  { cat:'quran', level:2, n:'sabr', w:{de:'al-ʿAṣr',tr:'Asr',en:'al-ʿAṣr',ar:'العصر'}, h:{de:'die Zeit',tr:'zaman',en:'time & loss',ar:'الزمن'} },
  { cat:'quran', level:3, n:'isa', w:{de:'Maryam (Sure)',tr:'Meryem (sûre)',en:'Maryam (surah)',ar:'مريم'}, h:{de:'Mutter von ʿÎsâ',tr:'İsa’nın annesi',en:'mother of ʿÎsâ',ar:'أم عيسى'} },
  { cat:'quran', level:3, n:'mecca_kaaba', w:{de:'al-Fîl',tr:'Fîl',en:'al-Fîl',ar:'الفيل'}, h:{de:'die Elefanten',tr:'fil ordusu',en:'the elephant',ar:'أصحاب الفيل'} },
  { cat:'quran', level:3, n:'mecca_kaaba', w:{de:'Quraysh',tr:'Kureyş',en:'Quraysh',ar:'قريش'}, h:{de:'Stamm des Propheten ﷺ',tr:'Peygamber’in kabilesi',en:'the Prophet’s tribe ﷺ',ar:'قبيلة النبي ﷺ'} },
  { cat:'quran', level:3, n:'victory', w:{de:'an-Naṣr',tr:'Nasr',en:'an-Naṣr',ar:'النصر'}, h:{de:'Hilfe & Sieg',tr:'yardım ve fetih',en:'help & victory',ar:'النصر والفتح'} },
  { cat:'quran', level:4, n:'qiyama', w:{de:'al-Wâqiʿa',tr:'Vâkıa',en:'al-Wâqiʿa',ar:'الواقعة'}, h:{de:'das Ereignis',tr:'olacak olay',en:'the inevitable',ar:'يوم القيامة'} },
  { cat:'quran', level:4, n:'taqwa', w:{de:'al-Ḥujurât',tr:'Hucurât',en:'al-Ḥujurât',ar:'الحجرات'}, h:{de:'Sure des Adab',tr:'edep sûresi',en:'surah of manners',ar:'سورة الأدب'} },

  /* ===== Heilige Orte (weitere) ===== */
  { cat:'places', level:4, n:'first_revelation', w:{de:'Jabal an-Nûr',tr:'Nur Dağı',en:'Jabal an-Nûr',ar:'جبل النور'}, h:{de:'Berg der Höhle Ḥirâʾ',tr:'Hira dağı',en:'mount of Ḥirâʾ',ar:'فيه غار حراء'} },
  { cat:'places', level:4, n:'tawakkul', w:{de:'Ghâr Thawr',tr:'Sevr Mağarası',en:'Ghâr Thawr',ar:'غار ثور'}, h:{de:'Höhle der Hijra',tr:'hicret mağarası',en:'cave of the Hijra',ar:'في الهجرة'} },
  { cat:'places', level:4, n:'hajj', w:{de:'Muzdalifa',tr:'Müzdelife',en:'Muzdalifa',ar:'مزدلفة'}, h:{de:'Station beim Ḥajj',tr:'hac durağı',en:'a Hajj station',ar:'المشعر الحرام'} },
  { cat:'places', level:3, n:'mecca_kaaba', w:{de:'al-Ḥajar al-Aswad',tr:'Hacerü’l-Esved',en:'the Black Stone',ar:'الحجر الأسود'}, h:{de:'der schwarze Stein',tr:'siyah taş',en:'the black stone',ar:'ركن الكعبة'} },
  { cat:'places', level:4, n:'ibrahim', w:{de:'Maqâm Ibrâhîm',tr:'Makam-ı İbrahim',en:'Maqâm Ibrâhîm',ar:'مقام إبراهيم'}, h:{de:'Stätte Ibrâhîms',tr:'İbrahim’in makamı',en:'station of Ibrâhîm',ar:'أثر إبراهيم'} },
  { cat:'places', level:2, n:'mecca_kaaba', w:{de:'Baytullâh',tr:'Beytullah',en:'Baytullâh',ar:'بيت الله'}, h:{de:'Haus Allahs',tr:'Allah’ın evi',en:'House of Allah',ar:'الكعبة'} },

  /* ===== Charakter (weitere) ===== */
  { cat:'akhlaq', level:2, n:'zakat_salah', w:{de:'Karam (Freigebigkeit)',tr:'Kerem (Cömertlik)',en:'Karam (Generosity)',ar:'الكرم'}, h:{de:'Großzügigkeit',tr:'cömertlik',en:'generosity',ar:'السخاء'} },
  { cat:'akhlaq', level:2, n:'taqwa', w:{de:'ʿAdl (Gerechtigkeit)',tr:'Adl (Adalet)',en:'ʿAdl (Justice)',ar:'العدل'}, h:{de:'Gerechtigkeit',tr:'adalet',en:'justice',ar:'الإنصاف'} },
  { cat:'akhlaq', level:4, n:'love_brother', w:{de:'Îthâr (Selbstlosigkeit)',tr:'Îsâr (Diğergamlık)',en:'Îthâr (Altruism)',ar:'الإيثار'}, h:{de:'andere bevorzugen',tr:'başkasını tercih',en:'preferring others',ar:'تفضيل الغير'} },
  { cat:'akhlaq', level:3, n:'love_brother', w:{de:'Ḥusn aẓ-Ẓann',tr:'Hüsn-i Zan',en:'Ḥusn aẓ-Ẓann',ar:'حسن الظن'}, h:{de:'gute Annahme',tr:'iyi zan',en:'good assumption',ar:'الظن الحسن'} },
  { cat:'akhlaq', level:3, n:'shukr', w:{de:'Qanâʿa (Genügsamkeit)',tr:'Kanaat',en:'Qanâʿa (Contentment)',ar:'القناعة'}, h:{de:'Zufriedenheit',tr:'yetinme',en:'contentment',ar:'الرضا'} },
  { cat:'akhlaq', level:3, n:'muslim_safe', w:{de:'Wafâʾ (Treue)',tr:'Vefâ',en:'Wafâʾ (Faithfulness)',ar:'الوفاء'}, h:{de:'sein Wort halten',tr:'söz tutmak',en:'keeping one’s word',ar:'الوفاء بالعهد'} },

  /* ===== Glaube & Jenseits (ʿAqîda) ===== */
  { cat:'aqida', level:1, n:'tawhid', w:{de:'Allâh',tr:'Allah',en:'Allâh',ar:'الله'}, h:{de:'der eine Schöpfer',tr:'tek Yaratan',en:'the One Creator',ar:'الخالق الواحد'} },
  { cat:'aqida', level:1, n:'iman_pillars', w:{de:'Malâʾika (Engel)',tr:'Melekler',en:'Malâʾika (Angels)',ar:'الملائكة'}, h:{de:'aus Licht erschaffen',tr:'nurdan yaratıldı',en:'made of light',ar:'خُلقوا من نور'} },
  { cat:'aqida', level:1, n:'iman_pillars', w:{de:'Jibrîl',tr:'Cebrâil',en:'Jibrîl',ar:'جبريل'}, h:{de:'Engel der Offenbarung',tr:'vahiy meleği',en:'angel of revelation',ar:'ملك الوحي'} },
  { cat:'aqida', level:3, n:'iman_pillars', w:{de:'Mîkâʾîl',tr:'Mîkâil',en:'Mîkâʾîl',ar:'ميكائيل'}, h:{de:'Regen & Versorgung',tr:'yağmur ve rızık',en:'rain & provision',ar:'موكّل بالرزق'} },
  { cat:'aqida', level:3, n:'qiyama', w:{de:'Isrâfîl',tr:'İsrâfil',en:'Isrâfîl',ar:'إسرافيل'}, h:{de:'bläst ins Horn',tr:'sûra üfleyen',en:'blows the trumpet',ar:'النفخ في الصور'} },
  { cat:'aqida', level:2, n:'iman_pillars', w:{de:'Kutub (Bücher)',tr:'Kitaplar',en:'Kutub (Books)',ar:'الكتب'}, h:{de:'offenbarte Schriften',tr:'ilahî kitaplar',en:'revealed books',ar:'الوحي'} },
  { cat:'aqida', level:2, n:'musa', w:{de:'Tawrât',tr:'Tevrat',en:'Tawrât',ar:'التوراة'}, h:{de:'Buch von Mûsâ',tr:'Mûsâ’nın kitabı',en:'book of Mûsâ',ar:'كتاب موسى'} },
  { cat:'aqida', level:2, n:'isa', w:{de:'Injîl',tr:'İncil',en:'Injîl',ar:'الإنجيل'}, h:{de:'Buch von ʿÎsâ',tr:'İsa’nın kitabı',en:'book of ʿÎsâ',ar:'كتاب عيسى'} },
  { cat:'aqida', level:3, n:'prophets_guided', w:{de:'Zabûr',tr:'Zebûr',en:'Zabûr',ar:'الزبور'}, h:{de:'Buch von Dâwûd',tr:'Dâvûd’un kitabı',en:'book of Dâwûd',ar:'كتاب داود'} },
  { cat:'aqida', level:1, n:'janna', w:{de:'Janna (Paradies)',tr:'Cennet',en:'Janna (Paradise)',ar:'الجنة'}, h:{de:'der ewige Garten',tr:'ebedî bahçe',en:'the eternal garden',ar:'الفردوس'} },
  { cat:'aqida', level:2, n:'taqwa', w:{de:'Jahannam (Hölle)',tr:'Cehennem',en:'Jahannam (Hellfire)',ar:'جهنم'}, h:{de:'das Feuer',tr:'ateş',en:'the Fire',ar:'النار'} },
  { cat:'aqida', level:2, n:'qiyama', w:{de:'Yawm al-Qiyâma',tr:'Kıyamet Günü',en:'Yawm al-Qiyâma',ar:'يوم القيامة'}, h:{de:'Tag der Auferstehung',tr:'diriliş günü',en:'Day of Resurrection',ar:'يوم البعث'} },
  { cat:'aqida', level:3, n:'qiyama', w:{de:'al-Mîzân',tr:'Mîzan',en:'al-Mîzân',ar:'الميزان'}, h:{de:'Waage der Taten',tr:'amel terazisi',en:'the scale of deeds',ar:'ميزان الأعمال'} },
  { cat:'aqida', level:4, n:'qiyama', w:{de:'aṣ-Ṣirâṭ',tr:'Sırat',en:'aṣ-Ṣirâṭ',ar:'الصراط'}, h:{de:'die Brücke',tr:'köprü',en:'the bridge',ar:'الجسر'} },
  { cat:'aqida', level:3, n:'iman_pillars', w:{de:'al-Qadar',tr:'Kader',en:'al-Qadar',ar:'القدر'}, h:{de:'göttliche Vorherbestimmung',tr:'ilahî takdir',en:'divine decree',ar:'القضاء والقدر'} },
  { cat:'aqida', level:4, n:'qiyama', w:{de:'al-Barzakh',tr:'Berzah',en:'al-Barzakh',ar:'البرزخ'}, h:{de:'Zwischenwelt (Grab)',tr:'kabir âlemi',en:'the intermediate realm',ar:'ما بعد الموت'} },

  /* ===== Sîra & Geschichte ===== */
  { cat:'history', level:1, n:'tawakkul', w:{de:'al-Hijra',tr:'Hicret',en:'al-Hijra',ar:'الهجرة'}, h:{de:'Auswanderung nach Medina',tr:'Medine’ye göç',en:'migration to Madinah',ar:'إلى المدينة'} },
  { cat:'history', level:1, n:'badr', w:{de:'Badr',tr:'Bedir',en:'Badr',ar:'بدر'}, h:{de:'erste große Schlacht',tr:'ilk büyük savaş',en:'first major battle',ar:'أول غزوة كبرى'} },
  { cat:'history', level:2, n:'sabr', w:{de:'Uḥud',tr:'Uhud',en:'Uḥud',ar:'أحد'}, h:{de:'zweite Schlacht',tr:'ikinci savaş',en:'second battle',ar:'الغزوة الثانية'} },
  { cat:'history', level:3, n:'tawakkul', w:{de:'al-Khandaq',tr:'Hendek',en:'al-Khandaq',ar:'الخندق'}, h:{de:'der Graben',tr:'siper savaşı',en:'the trench',ar:'الأحزاب'} },
  { cat:'history', level:2, n:'victory', w:{de:'Fatḥ Makka',tr:'Mekke’nin Fethi',en:'Conquest of Makkah',ar:'فتح مكة'}, h:{de:'Eroberung Mekkas',tr:'Mekke fethi',en:'conquest of Mecca',ar:'دخول مكة'} },
  { cat:'history', level:3, n:'victory', w:{de:'al-Ḥudaybiya',tr:'Hudeybiye',en:'al-Ḥudaybiya',ar:'الحديبية'}, h:{de:'der Vertrag',tr:'antlaşma',en:'the treaty',ar:'الصلح'} },
  { cat:'history', level:2, n:'aqsa_isra', w:{de:'al-Isrâʾ waʾl-Miʿrâj',tr:'İsrâ ve Mi’râc',en:'al-Isrâʾ & Miʿrâj',ar:'الإسراء والمعراج'}, h:{de:'die Nachtreise',tr:'gece yolculuğu',en:'the night journey',ar:'رحلة الليل'} },
  { cat:'history', level:3, n:'hajj', w:{de:'Ḥajjat al-Wadâʿ',tr:'Vedâ Haccı',en:'the Farewell Ḥajj',ar:'حجة الوداع'}, h:{de:'letzte Pilgerfahrt',tr:'son hac',en:'the final pilgrimage',ar:'آخر حج'} },
  { cat:'history', level:3, n:'mecca_kaaba', w:{de:'ʿÂm al-Fîl',tr:'Fil Yılı',en:'Year of the Elephant',ar:'عام الفيل'}, h:{de:'Geburtsjahr des Propheten ﷺ',tr:'Peygamber’in doğum yılı',en:'the Prophet’s birth year ﷺ',ar:'مولد النبي ﷺ'} },
  { cat:'history', level:4, n:'muslim_safe', w:{de:'Bayʿat al-ʿAqaba',tr:'Akabe Biatı',en:'Pledge of al-ʿAqaba',ar:'بيعة العقبة'}, h:{de:'der Treueeid',tr:'biat',en:'the pledge',ar:'العهد'} },
  { cat:'history', level:1, n:'ramadan', w:{de:'Ramaḍân',tr:'Ramazan',en:'Ramaḍân',ar:'رمضان'}, h:{de:'Monat des Fastens',tr:'oruç ayı',en:'month of fasting',ar:'شهر الصيام'} },
  { cat:'history', level:2, n:'laylatqadr', w:{de:'Laylat al-Qadr',tr:'Kadir Gecesi',en:'Laylat al-Qadr',ar:'ليلة القدر'}, h:{de:'Nacht der Bestimmung',tr:'bin aydan hayırlı',en:'night of decree',ar:'خير من ألف شهر'} },
  { cat:'history', level:2, n:'sawm', w:{de:'ʿÎd al-Fiṭr',tr:'Ramazan Bayramı',en:'ʿÎd al-Fiṭr',ar:'عيد الفطر'}, h:{de:'Fest des Fastenbrechens',tr:'oruç bayramı',en:'feast of breaking the fast',ar:'بعد رمضان'} },
  { cat:'history', level:2, n:'hajj', w:{de:'ʿÎd al-Aḍḥâ',tr:'Kurban Bayramı',en:'ʿÎd al-Aḍḥâ',ar:'عيد الأضحى'}, h:{de:'Opferfest',tr:'kurban bayramı',en:'feast of sacrifice',ar:'الأضحية'} },
  { cat:'history', level:3, n:'musa', w:{de:'ʿÂshûrâʾ',tr:'Aşure',en:'ʿÂshûrâʾ',ar:'عاشوراء'}, h:{de:'10. Muḥarram',tr:'Muharrem’in 10’u',en:'10th of Muḥarram',ar:'عاشر محرم'} },
  { cat:'history', level:4, n:'tawakkul', w:{de:'Ghazwat Tabûk',tr:'Tebük Seferi',en:'Expedition of Tabûk',ar:'غزوة تبوك'}, h:{de:'Feldzug in der Hitze',tr:'sıcakta sefer',en:'march in the heat',ar:'في شدة الحر'} },

  /* ===== Gegenstände ===== */
  { cat:'objects', level:1, n:'creation', w:{de:'Stuhl',tr:'Sandalye',en:'Chair',ar:'كرسي'}, h:{de:'zum Sitzen',tr:'oturmak için',en:'for sitting',ar:'للجلوس'} },
  { cat:'objects', level:1, n:'creation', w:{de:'Tisch',tr:'Masa',en:'Table',ar:'طاولة'}, h:{de:'zum Essen & Schreiben',tr:'yemek & yazı',en:'to eat & write',ar:'للطعام'} },
  { cat:'objects', level:1, n:'creation', w:{de:'Uhr',tr:'Saat',en:'Clock',ar:'ساعة'}, h:{de:'zeigt die Zeit',tr:'zamanı gösterir',en:'shows the time',ar:'الوقت'} },
  { cat:'objects', level:1, n:'creation', w:{de:'Schlüssel',tr:'Anahtar',en:'Key',ar:'مفتاح'}, h:{de:'öffnet die Tür',tr:'kapıyı açar',en:'opens the door',ar:'يفتح الباب'} },
  { cat:'objects', level:2, n:'creation', w:{de:'Lampe',tr:'Lamba',en:'Lamp',ar:'مصباح'}, h:{de:'gibt Licht',tr:'ışık verir',en:'gives light',ar:'النور'} },
  { cat:'objects', level:2, n:'knowledge', w:{de:'Buch',tr:'Kitap',en:'Book',ar:'كتاب'}, h:{de:'zum Lesen',tr:'okumak için',en:'for reading',ar:'للقراءة'} },
  { cat:'objects', level:1, n:'creation', w:{de:'Tür',tr:'Kapı',en:'Door',ar:'باب'}, h:{de:'der Eingang',tr:'giriş',en:'entrance',ar:'المدخل'} },
  { cat:'objects', level:2, n:'salah', w:{de:'Gebetsteppich',tr:'Seccade',en:'Prayer rug',ar:'سجادة'}, h:{de:'zum Beten',tr:'namaz için',en:'for prayer',ar:'للصلاة'} },

  /* ===== Tiere ===== */
  { cat:'animals', level:1, n:'creation', w:{de:'Katze',tr:'Kedi',en:'Cat',ar:'قطة'}, h:{de:'miaut',tr:'miyavlar',en:'meows',ar:'تموء'} },
  { cat:'animals', level:2, n:'creation', w:{de:'Pferd',tr:'At',en:'Horse',ar:'حصان'}, h:{de:'zum Reiten',tr:'binmek için',en:'for riding',ar:'للركوب'} },
  { cat:'animals', level:1, n:'creation', w:{de:'Kamel',tr:'Deve',en:'Camel',ar:'جمل'}, h:{de:'Schiff der Wüste',tr:'çöl gemisi',en:'ship of the desert',ar:'سفينة الصحراء'} },
  { cat:'animals', level:2, n:'creation', w:{de:'Schaf',tr:'Koyun',en:'Sheep',ar:'خروف'}, h:{de:'gibt Wolle',tr:'yün verir',en:'gives wool',ar:'الصوف'} },
  { cat:'animals', level:2, n:'creation', w:{de:'Biene',tr:'Arı',en:'Bee',ar:'نحلة'}, h:{de:'macht Honig',tr:'bal yapar',en:'makes honey',ar:'العسل'} },
  { cat:'animals', level:3, n:'creation', w:{de:'Ameise',tr:'Karınca',en:'Ant',ar:'نملة'}, h:{de:'klein & fleißig',tr:'küçük & çalışkan',en:'tiny & busy',ar:'صغيرة'} },
  { cat:'animals', level:2, n:'creation', w:{de:'Vogel',tr:'Kuş',en:'Bird',ar:'طائر'}, h:{de:'fliegt',tr:'uçar',en:'flies',ar:'يطير'} },
  { cat:'animals', level:1, n:'provision', w:{de:'Fisch',tr:'Balık',en:'Fish',ar:'سمكة'}, h:{de:'im Wasser',tr:'suda',en:'in the water',ar:'في الماء'} },

  /* ===== Obst, Gemüse & Speisen ===== */
  { cat:'food', level:1, n:'provision', w:{de:'Apfel',tr:'Elma',en:'Apple',ar:'تفاح'}, h:{de:'rot oder grün',tr:'kırmızı/yeşil',en:'red or green',ar:'فاكهة'} },
  { cat:'food', level:1, n:'provision', w:{de:'Dattel',tr:'Hurma',en:'Date',ar:'تمر'}, h:{de:'süß, Sunna-Frucht',tr:'tatlı, sünnet',en:'sweet, Sunnah fruit',ar:'حلوة'} },
  { cat:'food', level:2, n:'provision', w:{de:'Traube',tr:'Üzüm',en:'Grape',ar:'عنب'}, h:{de:'in Trauben',tr:'salkım',en:'in bunches',ar:'عناقيد'} },
  { cat:'food', level:2, n:'provision', w:{de:'Feige',tr:'İncir',en:'Fig',ar:'تين'}, h:{de:'im Qurʾân erwähnt',tr:'Kurʾân’da',en:'in the Qurʾân',ar:'سورة التين'} },
  { cat:'food', level:2, n:'provision', w:{de:'Olive',tr:'Zeytin',en:'Olive',ar:'زيتون'}, h:{de:'gesegneter Baum',tr:'mübarek ağaç',en:'blessed tree',ar:'شجرة مباركة'} },
  { cat:'food', level:3, n:'provision', w:{de:'Granatapfel',tr:'Nar',en:'Pomegranate',ar:'رمان'}, h:{de:'viele Kerne',tr:'çok çekirdek',en:'many seeds',ar:'حبات'} },
  { cat:'food', level:2, n:'provision', w:{de:'Honig',tr:'Bal',en:'Honey',ar:'عسل'}, h:{de:'von der Biene, Heilung',tr:'arıdan, şifa',en:'from bees, a healing',ar:'شفاء'} },
  { cat:'food', level:1, n:'provision', w:{de:'Brot',tr:'Ekmek',en:'Bread',ar:'خبز'}, h:{de:'Grundnahrung',tr:'temel gıda',en:'staple food',ar:'الطعام'} },

  /* ===== Berufe ===== */
  { cat:'jobs', level:1, n:'knowledge', w:{de:'Lehrer',tr:'Öğretmen',en:'Teacher',ar:'معلّم'}, h:{de:'lehrt Wissen',tr:'ilim öğretir',en:'teaches knowledge',ar:'يعلّم'} },
  { cat:'jobs', level:1, n:'muslim_safe', w:{de:'Arzt',tr:'Doktor',en:'Doctor',ar:'طبيب'}, h:{de:'heilt Kranke',tr:'hastayı iyileştirir',en:'heals the sick',ar:'يعالج'} },
  { cat:'jobs', level:2, n:'provision', w:{de:'Bäcker',tr:'Fırıncı',en:'Baker',ar:'خبّاز'}, h:{de:'backt Brot',tr:'ekmek yapar',en:'bakes bread',ar:'يخبز'} },
  { cat:'jobs', level:2, n:'provision', w:{de:'Bauer',tr:'Çiftçi',en:'Farmer',ar:'مزارع'}, h:{de:'bestellt das Feld',tr:'tarla eker',en:'works the land',ar:'يزرع'} },
  { cat:'jobs', level:2, n:'muslim_safe', w:{de:'Kaufmann',tr:'Tüccar',en:'Merchant',ar:'تاجر'}, h:{de:'ehrlicher Handel',tr:'dürüst ticaret',en:'honest trade',ar:'التجارة'} },
  { cat:'jobs', level:3, n:'muslim_safe', w:{de:'Schmied',tr:'Demirci',en:'Blacksmith',ar:'حدّاد'}, h:{de:'arbeitet mit Eisen',tr:'demir işler',en:'works iron',ar:'الحديد'} },
  { cat:'jobs', level:1, n:'salah', w:{de:'Imâm',tr:'İmam',en:'Imam',ar:'إمام'}, h:{de:'leitet das Gebet',tr:'namaz kıldırır',en:'leads the prayer',ar:'يؤمّ الصلاة'} },
  { cat:'jobs', level:2, n:'muslim_safe', w:{de:'Schneider',tr:'Terzi',en:'Tailor',ar:'خيّاط'}, h:{de:'näht Kleidung',tr:'elbise diker',en:'sews clothes',ar:'يخيط'} },

  /* ===== Menschen ===== */
  { cat:'people', level:1, n:'parents', w:{de:'Mutter',tr:'Anne',en:'Mother',ar:'أم'}, h:{de:'Paradies zu ihren Füßen',tr:'ayağı altında cennet',en:'Paradise at her feet',ar:'الجنة تحت قدميها'} },
  { cat:'people', level:1, n:'parents', w:{de:'Vater',tr:'Baba',en:'Father',ar:'أب'}, h:{de:'Güte gebührt ihm',tr:'iyilik hakkı',en:'kindness is his right',ar:'بِرّه'} },
  { cat:'people', level:2, n:'love_brother', w:{de:'Nachbar',tr:'Komşu',en:'Neighbor',ar:'جار'}, h:{de:'hat große Rechte',tr:'komşu hakkı',en:'has great rights',ar:'حق الجار'} },
  { cat:'people', level:2, n:'good_word', w:{de:'Gast',tr:'Misafir',en:'Guest',ar:'ضيف'}, h:{de:'ehre ihn',tr:'ikram et',en:'honour him',ar:'أكرم ضيفك'} },
  { cat:'people', level:2, n:'love_brother', w:{de:'Waise',tr:'Yetim',en:'Orphan',ar:'يتيم'}, h:{de:'nicht bedrängen',tr:'incitme',en:'do not oppress',ar:'لا تقهره'} },
  { cat:'people', level:1, n:'love_brother', w:{de:'Freund',tr:'Arkadaş',en:'Friend',ar:'صديق'}, h:{de:'guter Umgang',tr:'iyi arkadaş',en:'good company',ar:'الصحبة'} },
  { cat:'people', level:3, n:'love_brother', w:{de:'Reisender',tr:'Yolcu',en:'Traveler',ar:'مسافر'}, h:{de:'hat Anrecht auf Hilfe',tr:'yolcu hakkı',en:'has a right to help',ar:'ابن السبيل'} },
  { cat:'people', level:1, n:'prophet_mercy', w:{de:'Kind',tr:'Çocuk',en:'Child',ar:'طفل'}, h:{de:'zeige Barmherzigkeit',tr:'merhamet göster',en:'show mercy',ar:'الرحمة'} },

  /* ===== Gute Taten ===== */
  { cat:'good_deeds', level:1, n:'love_brother', w:{de:'Lächeln',tr:'Tebessüm',en:'Smiling',ar:'التبسّم'}, h:{de:'ist eine Sadaqa',tr:'sadakadır',en:'is a charity',ar:'صدقة'} },
  { cat:'good_deeds', level:1, n:'muslim_safe', w:{de:'Salâm geben',tr:'Selam vermek',en:'Giving Salâm',ar:'إفشاء السلام'}, h:{de:'Frieden verbreiten',tr:'selamı yaymak',en:'spread peace',ar:'السلام'} },
  { cat:'good_deeds', level:1, n:'love_brother', w:{de:'Helfen',tr:'Yardım etmek',en:'Helping',ar:'المساعدة'}, h:{de:'dem Bruder beistehen',tr:'kardeşe yardım',en:'aid a brother',ar:'العون'} },
  { cat:'good_deeds', level:2, n:'love_brother', w:{de:'Krankenbesuch',tr:'Hasta ziyareti',en:'Visiting the sick',ar:'عيادة المريض'}, h:{de:'ein Recht des Muslims',tr:'müslümanın hakkı',en:'a right of the Muslim',ar:'حق'} },
  { cat:'good_deeds', level:1, n:'zakat_salah', w:{de:'Spenden',tr:'Sadaka vermek',en:'Giving charity',ar:'التصدّق'}, h:{de:'für Allah geben',tr:'Allah için vermek',en:'give for Allah',ar:'في سبيل الله'} },
  { cat:'good_deeds', level:2, n:'good_word', w:{de:'Vergeben',tr:'Affetmek',en:'Forgiving',ar:'العفو'}, h:{de:'verzeihen',tr:'bağışlamak',en:'to pardon',ar:'الصفح'} },
  { cat:'good_deeds', level:2, n:'quran_guidance', w:{de:'Qurʾân lesen',tr:'Kurʾân okumak',en:'Reciting Qurʾân',ar:'تلاوة القرآن'}, h:{de:'Lohn je Buchstabe',tr:'her harfe sevap',en:'reward per letter',ar:'بكل حرف حسنة'} },
  { cat:'good_deeds', level:2, n:'salawat', w:{de:'Ṣalawât sprechen',tr:'Salavat getirmek',en:'Sending Ṣalawât',ar:'الصلاة على النبي ﷺ'}, h:{de:'auf den Propheten ﷺ',tr:'Peygamber’e ﷺ',en:'upon the Prophet ﷺ',ar:'اللهم صلِّ عليه'} },

  /* ===== Sünden & Harâm (zu erkennen und zu meiden) ===== */
  { cat:'bad_deeds', level:1, n:'good_word', w:{de:'Lügen',tr:'Yalan',en:'Lying',ar:'الكذب'}, h:{de:'meide es',tr:'kaçın',en:'avoid it',ar:'تجنّبه'} },
  { cat:'bad_deeds', level:2, n:'avoid_sin', w:{de:'Stehlen',tr:'Hırsızlık',en:'Stealing',ar:'السرقة'}, h:{de:'verboten',tr:'haram',en:'forbidden',ar:'حرام'} },
  { cat:'bad_deeds', level:2, n:'avoid_sin', w:{de:'Neid',tr:'Haset',en:'Envy',ar:'الحسد'}, h:{de:'verzehrt das Gute',tr:'iyiliği yer',en:'consumes good deeds',ar:'يأكل الحسنات'} },
  { cat:'bad_deeds', level:2, n:'taqwa', w:{de:'Hochmut',tr:'Kibir',en:'Arrogance',ar:'الكِبر'}, h:{de:'hält vom Paradies ab',tr:'cennete engel',en:'bars from Paradise',ar:'يمنع الجنة'} },
  { cat:'bad_deeds', level:2, n:'good_word', w:{de:'Üble Nachrede (Ghîba)',tr:'Gıybet',en:'Backbiting (Ghîba)',ar:'الغيبة'}, h:{de:'über Abwesende reden',tr:'arkadan konuşmak',en:'of the absent',ar:'أكل لحم الأخ'} },
  { cat:'bad_deeds', level:3, n:'avoid_sin', w:{de:'Zins (Ribâ)',tr:'Faiz (Ribâ)',en:'Usury (Ribâ)',ar:'الربا'}, h:{de:'streng verboten',tr:'şiddetle haram',en:'strictly forbidden',ar:'محرّم'} },
  { cat:'bad_deeds', level:3, n:'avoid_sin', w:{de:'Glücksspiel',tr:'Kumar',en:'Gambling',ar:'الميسر'}, h:{de:'Ḥarâm',tr:'haram',en:'forbidden',ar:'القمار'} },
  { cat:'bad_deeds', level:2, n:'good_word', w:{de:'Zorn',tr:'Öfke',en:'Anger',ar:'الغضب'}, h:{de:'beherrsche ihn',tr:'öfkeni yen',en:'control it',ar:'اضبطه'} },
];

/* =================================================================
   BILGI YARIŞI — Wissensquiz (islamische Multiple-Choice-Fragen)
   c = Index der richtigen Antwort (0-basiert). Die Reihenfolge der
   Antworten wird im Spiel zufällig gemischt.
   e = kurze Erklärung (zum Lernen) · ref = Quelle (optional)
   ================================================================= */
const QUIZ_CATEGORIES = [
  { id:'aqida',   icon: ICONS.aqida,   name:{de:'Glaube & Tawhîd', tr:'İman & Tevhid',  en:'Faith & Tawhîd',  ar:'العقيدة والتوحيد'} },
  { id:'quran',   icon: ICONS.quran,   name:{de:'Qurʾân',          tr:'Kurʾân',          en:'Qurʾân',          ar:'القرآن'} },
  { id:'seerah',  icon: ICONS.history, name:{de:'Prophetenleben',  tr:'Siyer',           en:'Life of the Prophet ﷺ', ar:'السيرة النبوية'} },
  { id:'fiqh',    icon: ICONS.worship, name:{de:'Gottesdienst',    tr:'İbadet & Fıkıh',  en:'Worship & Fiqh',  ar:'العبادات والفقه'} },
  { id:'akhlaq',  icon: ICONS.akhlaq,  name:{de:'Charakter & Ḥalâl', tr:'Ahlak & Helal', en:'Character & Ḥalâl', ar:'الأخلاق والحلال'} },
  { id:'general', icon: ICONS.mixed,   name:{de:'Allgemein',       tr:'Genel',           en:'General',         ar:'معلومات عامة'} },
];

const QUIZ = [
  /* ===== ʿAqîda / Tawhîd ===== */
  { cat:'aqida', level:1, c:1, ref:'Muslim 8',
    q:{de:'Wie viele Säulen hat der Îmân (Glaube)?',tr:'İmanın kaç şartı vardır?',en:'How many pillars of Îmân (faith) are there?',ar:'كم عدد أركان الإيمان؟'},
    o:[{de:'5',tr:'5',en:'5',ar:'٥'},{de:'6',tr:'6',en:'6',ar:'٦'},{de:'7',tr:'7',en:'7',ar:'٧'},{de:'3',tr:'3',en:'3',ar:'٣'}],
    e:{de:'Sechs: Glaube an Allah, die Engel, die Bücher, die Gesandten, den Jüngsten Tag und das Qadar.',tr:'Altı: Allah’a, meleklere, kitaplara, peygamberlere, ahirete ve kadere iman.',en:'Six: belief in Allah, the angels, the books, the messengers, the Last Day and the divine decree.',ar:'ستة: الإيمان بالله وملائكته وكتبه ورسله واليوم الآخر والقدر.'} },
  { cat:'aqida', level:1, c:0, ref:'Luqmân 31:13',
    q:{de:'Was ist die größte Sünde im Islam?',tr:'İslam’da en büyük günah nedir?',en:'What is the greatest sin in Islam?',ar:'ما أعظم ذنب في الإسلام؟'},
    o:[{de:'Schirk – Allah Partner beigesellen',tr:'Şirk – Allah’a ortak koşmak',en:'Shirk – associating partners with Allah',ar:'الشرك بالله'},{de:'Lügen',tr:'Yalan',en:'Lying',ar:'الكذب'},{de:'Diebstahl',tr:'Hırsızlık',en:'Theft',ar:'السرقة'},{de:'Verschlafen des Gebets',tr:'Namazı uyuyup kaçırmak',en:'Oversleeping a prayer',ar:'النوم عن الصلاة'}],
    e:{de:'Der Schirk ist das größte Unrecht – halte am reinen Tawhîd fest und meide jeden Schirk.',tr:'Şirk en büyük zulümdür – saf tevhide sarıl, şirkten kaçın.',en:'Shirk is the gravest wrong — hold firmly to pure Tawhîd and avoid all shirk.',ar:'الشرك أعظم الظلم؛ فتمسّك بالتوحيد الخالص واجتنب الشرك.'} },
  { cat:'aqida', level:1, c:0,
    q:{de:'Was bedeutet „Lâ ilâha illâ Allâh“?',tr:'“Lâ ilâhe illallâh” ne demektir?',en:'What does “Lâ ilâha illâ Allâh” mean?',ar:'ما معنى «لا إله إلا الله»؟'},
    o:[{de:'Kein (Anrecht auf Anbetung) außer Allah',tr:'Allah’tan başka (ibadete lâyık) ilah yoktur',en:'No (deity worthy of worship) except Allah',ar:'لا معبود بحق إلا الله'},{de:'Allah ist am größten',tr:'Allah en büyüktür',en:'Allah is the greatest',ar:'الله أكبر'},{de:'Lob sei Allah',tr:'Hamd Allah’adır',en:'Praise be to Allah',ar:'الحمد لله'},{de:'Im Namen Allahs',tr:'Allah’ın adıyla',en:'In the name of Allah',ar:'بسم الله'}],
    e:{de:'Das Wort des Tawhîd: Es gibt kein Recht auf Anbetung außer Allah allein.',tr:'Tevhid kelimesi: İbadete lâyık olan yalnız Allah’tır.',en:'The word of Tawhîd: none has the right to be worshipped except Allah alone.',ar:'كلمة التوحيد: لا يستحق العبادة إلا الله وحده.'} },
  { cat:'aqida', level:2, c:0,
    q:{de:'Welcher Engel ist mit der Offenbarung betraut?',tr:'Vahiyle görevli melek hangisidir?',en:'Which angel is entrusted with revelation?',ar:'أي ملك موكّل بالوحي؟'},
    o:[{de:'Jibrîl',tr:'Cebrâil',en:'Jibrîl',ar:'جبريل'},{de:'Mîkâʾîl',tr:'Mîkâil',en:'Mîkâʾîl',ar:'ميكائيل'},{de:'Isrâfîl',tr:'İsrâfil',en:'Isrâfîl',ar:'إسرافيل'},{de:'Mâlik',tr:'Mâlik',en:'Mâlik',ar:'مالك'}],
    e:{de:'Jibrîl (a.s.) überbrachte die Offenbarung an die Propheten.',tr:'Cebrâil (a.s.) vahyi peygamberlere getirdi.',en:'Jibrîl (a.s.) brought the revelation to the prophets.',ar:'جبريل عليه السلام نزل بالوحي على الأنبياء.'} },
  { cat:'aqida', level:2, c:0,
    q:{de:'Welches gehört NICHT zu den 6 Glaubenssäulen?',tr:'Aşağıdakilerden hangisi imanın 6 şartından DEĞİLDİR?',en:'Which is NOT one of the 6 pillars of faith?',ar:'أيٌّ مما يلي ليس من أركان الإيمان الستة؟'},
    o:[{de:'Glaube an den „Zufall“',tr:'“Tesadüfe” inanmak',en:'Belief in “coincidence”',ar:'الإيمان بـ«الصدفة»'},{de:'Glaube an die Engel',tr:'Meleklere iman',en:'Belief in the angels',ar:'الإيمان بالملائكة'},{de:'Glaube an die Bücher',tr:'Kitaplara iman',en:'Belief in the books',ar:'الإيمان بالكتب'},{de:'Glaube an das Qadar',tr:'Kadere iman',en:'Belief in the divine decree',ar:'الإيمان بالقدر'}],
    e:{de:'Es gibt keinen „Zufall“ – der Muslim glaubt an das Qadar, Allahs weise Vorherbestimmung.',tr:'“Tesadüf” yoktur – mümin kadere, Allah’ın hikmetli takdirine iman eder.',en:'There is no “coincidence” — a Muslim believes in Qadar, Allah’s wise decree.',ar:'لا «صدفة»؛ المسلم يؤمن بالقدر، تقدير الله الحكيم.'} },
  { cat:'aqida', level:3, c:0,
    q:{de:'Welche Schrift wurde Prophet Dâwûd (a.s.) gegeben?',tr:'Dâvûd (a.s.)’a hangi kitap verildi?',en:'Which scripture was given to Prophet Dâwûd (a.s.)?',ar:'أي كتاب أُنزل على داود عليه السلام؟'},
    o:[{de:'Zabûr',tr:'Zebûr',en:'Zabûr',ar:'الزبور'},{de:'Tawrât',tr:'Tevrat',en:'Tawrât',ar:'التوراة'},{de:'Injîl',tr:'İncil',en:'Injîl',ar:'الإنجيل'},{de:'Qurʾân',tr:'Kurʾân',en:'Qurʾân',ar:'القرآن'}],
    e:{de:'Zabûr → Dâwûd, Tawrât → Mûsâ, Injîl → ʿÎsâ, Qurʾân → Muḥammad ﷺ.',tr:'Zebûr → Dâvûd, Tevrat → Mûsâ, İncil → Îsâ, Kurʾân → Muhammed ﷺ.',en:'Zabûr → Dâwûd, Tawrât → Mûsâ, Injîl → ʿÎsâ, Qurʾân → Muḥammad ﷺ.',ar:'الزبور لداود، والتوراة لموسى، والإنجيل لعيسى، والقرآن لمحمد ﷺ.'} },
  { cat:'aqida', level:3, c:0, ref:'al-Kahf 18:110',
    q:{de:'Was ist „kleiner Schirk“, vor dem man sich hüten soll?',tr:'Kaçınılması gereken “küçük şirk” nedir?',en:'What is “minor shirk” that one must avoid?',ar:'ما هو «الشرك الأصغر» الذي يجب اجتنابه؟'},
    o:[{de:'Riyâʾ – Taten zur Schau stellen',tr:'Riyâ – ameli gösteriş için yapmak',en:'Riyâʾ – showing off deeds',ar:'الرياء – العمل للناس'},{de:'Zu spät kommen',tr:'Geç kalmak',en:'Being late',ar:'التأخّر'},{de:'Reisen am Freitag',tr:'Cuma günü seyahat',en:'Travelling on Friday',ar:'السفر يوم الجمعة'},{de:'Vergessen einer Sûra',tr:'Bir sûreyi unutmak',en:'Forgetting a sûrah',ar:'نسيان سورة'}],
    e:{de:'Riyâʾ (Anbetung, um gesehen zu werden) ist versteckter Schirk – halte an Ikhlâṣ (Aufrichtigkeit) fest.',tr:'Riyâ (görülmek için ibadet) gizli şirktir – ihlâsa sarıl.',en:'Riyâʾ (worship to be seen) is hidden shirk — hold to Ikhlâṣ (sincerity).',ar:'الرياء شركٌ خفيّ؛ فالزم الإخلاص.'} },
  { cat:'aqida', level:4, c:0, ref:'az-Zukhruf 43:77',
    q:{de:'Wie heißt der Engel, der über das Höllenfeuer gesetzt ist?',tr:'Cehennemin bekçisi olan meleğin adı nedir?',en:'What is the name of the angel over the Hellfire?',ar:'ما اسم الملك الموكّل بالنار؟'},
    o:[{de:'Mâlik',tr:'Mâlik',en:'Mâlik',ar:'مالك'},{de:'Riḍwân',tr:'Rıdvân',en:'Riḍwân',ar:'رضوان'},{de:'Munkar',tr:'Münker',en:'Munkar',ar:'منكر'},{de:'Isrâfîl',tr:'İsrâfil',en:'Isrâfîl',ar:'إسرافيل'}],
    e:{de:'Mâlik ist der Wärter des Feuers (az-Zukhruf 43:77).',tr:'Mâlik cehennemin bekçisidir (Zuhruf 43:77).',en:'Mâlik is the keeper of the Fire (az-Zukhruf 43:77).',ar:'مالك خازن النار (الزخرف ٤٣:٧٧).'} },

  /* ===== Qurʾân ===== */
  { cat:'quran', level:1, c:0,
    q:{de:'Wie viele Suren hat der Qurʾân?',tr:'Kurʾân’da kaç sûre vardır?',en:'How many sûrahs are in the Qurʾân?',ar:'كم عدد سور القرآن؟'},
    o:[{de:'114',tr:'114',en:'114',ar:'١١٤'},{de:'100',tr:'100',en:'100',ar:'١٠٠'},{de:'120',tr:'120',en:'120',ar:'١٢٠'},{de:'99',tr:'99',en:'99',ar:'٩٩'}],
    e:{de:'Der Qurʾân besteht aus 114 Suren.',tr:'Kurʾân 114 sûreden oluşur.',en:'The Qurʾân has 114 sûrahs.',ar:'القرآن مئة وأربع عشرة سورة.'} },
  { cat:'quran', level:1, c:0,
    q:{de:'Welche ist die erste Sure im Qurʾân?',tr:'Kurʾân’ın ilk sûresi hangisidir?',en:'Which is the first sûrah in the Qurʾân?',ar:'ما أول سورة في القرآن؟'},
    o:[{de:'al-Fâtiḥa',tr:'Fâtiha',en:'al-Fâtiḥa',ar:'الفاتحة'},{de:'al-Baqara',tr:'Bakara',en:'al-Baqara',ar:'البقرة'},{de:'an-Nâs',tr:'Nâs',en:'an-Nâs',ar:'الناس'},{de:'al-Ikhlâṣ',tr:'İhlâs',en:'al-Ikhlâṣ',ar:'الإخلاص'}],
    e:{de:'al-Fâtiḥa ist die eröffnende Sure des Qurʾân.',tr:'Fâtiha, Kurʾân’ın açılış sûresidir.',en:'al-Fâtiḥa is the opening sûrah of the Qurʾân.',ar:'الفاتحة هي فاتحة القرآن.'} },
  { cat:'quran', level:2, c:0, ref:'Bukhârî 5015',
    q:{de:'Welche Sure wiegt „ein Drittel des Qurʾân“?',tr:'Hangi sûre “Kurʾân’ın üçte biri”ne denktir?',en:'Which sûrah equals “a third of the Qurʾân”?',ar:'أي سورة تعدل «ثلث القرآن»؟'},
    o:[{de:'al-Ikhlâṣ',tr:'İhlâs',en:'al-Ikhlâṣ',ar:'الإخلاص'},{de:'al-Fâtiḥa',tr:'Fâtiha',en:'al-Fâtiḥa',ar:'الفاتحة'},{de:'Yâ Sîn',tr:'Yâsîn',en:'Yâ Sîn',ar:'يس'},{de:'al-Mulk',tr:'Mülk',en:'al-Mulk',ar:'الملك'}],
    e:{de:'Al-Ikhlâṣ entspricht einem Drittel des Qurʾân (Bukhârî 5015) – reines Tawhîd.',tr:'İhlâs, Kurʾân’ın üçte birine denktir (Buhârî 5015) – saf tevhid.',en:'Al-Ikhlâṣ equals a third of the Qurʾân (Bukhârî 5015) — pure Tawhîd.',ar:'الإخلاص تعدل ثلث القرآن (البخاري ٥٠١٥) – توحيد خالص.'} },
  { cat:'quran', level:2, c:0,
    q:{de:'Welche ist die längste Sure des Qurʾân?',tr:'Kurʾân’ın en uzun sûresi hangisidir?',en:'Which is the longest sûrah of the Qurʾân?',ar:'ما أطول سورة في القرآن؟'},
    o:[{de:'al-Baqara',tr:'Bakara',en:'al-Baqara',ar:'البقرة'},{de:'al-Fâtiḥa',tr:'Fâtiha',en:'al-Fâtiḥa',ar:'الفاتحة'},{de:'an-Nisâʾ',tr:'Nisâ',en:'an-Nisâʾ',ar:'النساء'},{de:'Âl ʿImrân',tr:'Âl-i İmrân',en:'Âl ʿImrân',ar:'آل عمران'}],
    e:{de:'al-Baqara ist mit 286 Âyât die längste Sure.',tr:'Bakara, 286 âyetle en uzun sûredir.',en:'al-Baqara is the longest sûrah with 286 verses.',ar:'البقرة أطول سورة، وفيها ٢٨٦ آية.'} },
  { cat:'quran', level:3, c:0,
    q:{de:'Wie viele Âyât hat der Qurʾân (Ḥafṣ-Zählung)?',tr:'Kurʾân’da (Hafs sayımı) kaç âyet vardır?',en:'How many verses does the Qurʾân have (Ḥafṣ count)?',ar:'كم عدد آيات القرآن (عدّ حفص)؟'},
    o:[{de:'6236',tr:'6236',en:'6236',ar:'٦٢٣٦'},{de:'6666',tr:'6666',en:'6666',ar:'٦٦٦٦'},{de:'6000',tr:'6000',en:'6000',ar:'٦٠٠٠'},{de:'5000',tr:'5000',en:'5000',ar:'٥٠٠٠'}],
    e:{de:'In der verbreiteten Ḥafṣ-Lesart sind es 6236 Âyât (die oft genannte „6666“ ist nicht belegt).',tr:'Yaygın Hafs rivayetinde 6236 âyettir (meşhur “6666” asılsızdır).',en:'In the common Ḥafṣ reading there are 6236 verses (the popular “6666” is unverified).',ar:'في رواية حفص المشهورة ٦٢٣٦ آية (والمشهور «٦٦٦٦» غير ثابت).'} },
  { cat:'quran', level:3, c:0, ref:'al-Qadr 97',
    q:{de:'In welcher Nacht begann die Herabsendung des Qurʾân?',tr:'Kurʾân’ın indirilişi hangi gecede başladı?',en:'On which night did the Qurʾân’s revelation begin?',ar:'في أي ليلة بدأ نزول القرآن؟'},
    o:[{de:'Laylat al-Qadr',tr:'Kadir Gecesi',en:'Laylat al-Qadr',ar:'ليلة القدر'},{de:'Laylat al-Barâʾa',tr:'Berat Gecesi',en:'Laylat al-Barâʾa',ar:'ليلة البراءة'},{de:'Freitagnacht',tr:'Cuma gecesi',en:'Friday night',ar:'ليلة الجمعة'},{de:'Laylat al-Isrâʾ',tr:'İsrâ gecesi',en:'Laylat al-Isrâʾ',ar:'ليلة الإسراء'}],
    e:{de:'In der Laylat al-Qadr (al-Qadr 97:1; al-Baqara 2:185).',tr:'Kadir Gecesinde (Kadr 97:1; Bakara 2:185).',en:'On Laylat al-Qadr (al-Qadr 97:1; al-Baqara 2:185).',ar:'في ليلة القدر (القدر ٩٧:١؛ البقرة ٢:١٨٥).'} },
  { cat:'quran', level:4, c:0,
    q:{de:'Welche Sure beginnt NICHT mit der Basmala?',tr:'Hangi sûre Besmele ile başlamaz?',en:'Which sûrah does NOT begin with the Basmala?',ar:'أي سورة لا تبدأ بالبسملة؟'},
    o:[{de:'at-Tawba',tr:'Tevbe',en:'at-Tawba',ar:'التوبة'},{de:'al-Fâtiḥa',tr:'Fâtiha',en:'al-Fâtiḥa',ar:'الفاتحة'},{de:'al-Ikhlâṣ',tr:'İhlâs',en:'al-Ikhlâṣ',ar:'الإخلاص'},{de:'an-Naml',tr:'Neml',en:'an-Naml',ar:'النمل'}],
    e:{de:'Sûrat at-Tawba ist die einzige Sure ohne einleitende Basmala.',tr:'Tevbe sûresi, başında Besmele bulunmayan tek sûredir.',en:'Sûrat at-Tawba is the only sûrah without an opening Basmala.',ar:'سورة التوبة هي الوحيدة التي لا تُفتتح بالبسملة.'} },

  /* ===== Sîra (Prophetenleben) ===== */
  { cat:'seerah', level:1, c:0,
    q:{de:'In welcher Stadt wurde der Prophet Muḥammad ﷺ geboren?',tr:'Peygamber ﷺ hangi şehirde doğdu?',en:'In which city was the Prophet Muḥammad ﷺ born?',ar:'في أي مدينة وُلد النبي محمد ﷺ؟'},
    o:[{de:'Makka',tr:'Mekke',en:'Makkah',ar:'مكة'},{de:'Madîna',tr:'Medine',en:'Madînah',ar:'المدينة'},{de:'aṭ-Ṭâʾif',tr:'Tâif',en:'aṭ-Ṭâʾif',ar:'الطائف'},{de:'Jerusalem',tr:'Kudüs',en:'Jerusalem',ar:'القدس'}],
    e:{de:'Der Prophet ﷺ wurde in Makka im „Jahr des Elefanten“ geboren.',tr:'Peygamber ﷺ, Fil Yılında Mekke’de doğdu.',en:'The Prophet ﷺ was born in Makkah in the Year of the Elephant.',ar:'وُلد النبي ﷺ في مكة عام الفيل.'} },
  { cat:'seerah', level:1, c:0,
    q:{de:'Wer war die erste Ehefrau des Propheten ﷺ und erste Gläubige?',tr:'Peygamber ﷺ’in ilk eşi ve ilk iman eden kimdir?',en:'Who was the Prophet’s ﷺ first wife and first believer?',ar:'من أول زوجات النبي ﷺ وأول من آمن؟'},
    o:[{de:'Khadîja',tr:'Hatice',en:'Khadîja',ar:'خديجة'},{de:'ʿÂʾisha',tr:'Âişe',en:'ʿÂʾisha',ar:'عائشة'},{de:'Ḥafṣa',tr:'Hafsa',en:'Ḥafṣa',ar:'حفصة'},{de:'Fâṭima',tr:'Fâtıma',en:'Fâṭima',ar:'فاطمة'}],
    e:{de:'Khadîja (r.a.) glaubte als Erste und stützte den Propheten ﷺ.',tr:'Hatice (r.a.) ilk iman eden ve Peygamber ﷺ’e destek olandır.',en:'Khadîja (r.a.) was the first to believe and supported the Prophet ﷺ.',ar:'خديجة رضي الله عنها أول من آمن وساندت النبي ﷺ.'} },
  { cat:'seerah', level:2, c:0,
    q:{de:'Wohin führte die Hijra des Propheten ﷺ?',tr:'Peygamber ﷺ’in hicreti nereye oldu?',en:'Where did the Prophet’s ﷺ Hijra lead?',ar:'إلى أين كانت هجرة النبي ﷺ؟'},
    o:[{de:'nach Madîna',tr:'Medine’ye',en:'to Madînah',ar:'إلى المدينة'},{de:'nach aṭ-Ṭâʾif',tr:'Tâif’e',en:'to aṭ-Ṭâʾif',ar:'إلى الطائف'},{de:'nach Ḥabasha',tr:'Habeşistan’a',en:'to Abyssinia',ar:'إلى الحبشة'},{de:'nach ash-Shâm',tr:'Şam’a',en:'to Shâm',ar:'إلى الشام'}],
    e:{de:'Die Hijra führte von Makka nach Madîna – Beginn der islamischen Zeitrechnung.',tr:'Hicret Mekke’den Medine’ye oldu – hicri takvimin başlangıcı.',en:'The Hijra went from Makkah to Madînah — start of the Islamic calendar.',ar:'كانت الهجرة من مكة إلى المدينة، وبها بدأ التقويم الهجري.'} },
  { cat:'seerah', level:2, c:0,
    q:{de:'Welcher Onkel zog den Propheten ﷺ nach dem Tod des Großvaters auf?',tr:'Dedesinin vefatından sonra Peygamber ﷺ’i hangi amcası büyüttü?',en:'Which uncle raised the Prophet ﷺ after his grandfather died?',ar:'أي عمٍّ كفل النبي ﷺ بعد وفاة جدّه؟'},
    o:[{de:'Abû Ṭâlib',tr:'Ebû Tâlib',en:'Abû Ṭâlib',ar:'أبو طالب'},{de:'Abû Lahab',tr:'Ebû Leheb',en:'Abû Lahab',ar:'أبو لهب'},{de:'Ḥamza',tr:'Hamza',en:'Ḥamza',ar:'حمزة'},{de:'al-ʿAbbâs',tr:'Abbâs',en:'al-ʿAbbâs',ar:'العباس'}],
    e:{de:'Abû Ṭâlib nahm ihn nach dem Tod von ʿAbd al-Muṭṭalib auf.',tr:'Abdülmuttalib’in vefatından sonra onu Ebû Tâlib himaye etti.',en:'Abû Ṭâlib took him in after ʿAbd al-Muṭṭalib passed away.',ar:'كفله أبو طالب بعد وفاة عبد المطلب.'} },
  { cat:'seerah', level:3, c:0,
    q:{de:'In welchem Jahr (n.H.) war die Schlacht von Badr?',tr:'Bedir Savaşı hicretin kaçıncı yılındaydı?',en:'In which year (AH) was the Battle of Badr?',ar:'في أي سنة (هـ) كانت غزوة بدر؟'},
    o:[{de:'2 n.H.',tr:'H. 2',en:'2 AH',ar:'٢ هـ'},{de:'5 n.H.',tr:'H. 5',en:'5 AH',ar:'٥ هـ'},{de:'8 n.H.',tr:'H. 8',en:'8 AH',ar:'٨ هـ'},{de:'10 n.H.',tr:'H. 10',en:'10 AH',ar:'١٠ هـ'}],
    e:{de:'Badr fand im 2. Jahr nach der Hijra statt – der erste große Sieg.',tr:'Bedir, hicretin 2. yılında oldu – ilk büyük zafer.',en:'Badr took place in 2 AH — the first major victory.',ar:'كانت بدر في السنة الثانية للهجرة، وهي أول نصر كبير.'} },
  { cat:'seerah', level:3, c:0,
    q:{de:'Wie viele Gefährten kämpften etwa bei Badr?',tr:'Bedir’de yaklaşık kaç sahâbe savaştı?',en:'About how many companions fought at Badr?',ar:'كم عدد الصحابة تقريبًا في بدر؟'},
    o:[{de:'etwa 313',tr:'yaklaşık 313',en:'about 313',ar:'نحو ٣١٣'},{de:'etwa 1000',tr:'yaklaşık 1000',en:'about 1000',ar:'نحو ١٠٠٠'},{de:'etwa 700',tr:'yaklaşık 700',en:'about 700',ar:'نحو ٧٠٠'},{de:'etwa 100',tr:'yaklaşık 100',en:'about 100',ar:'نحو ١٠٠'}],
    e:{de:'Rund 313 Muslime standen einer weit größeren Übermacht gegenüber – und siegten mit Allahs Hilfe.',tr:'Yaklaşık 313 Müslüman, kat kat büyük bir orduya karşı Allah’ın yardımıyla galip geldi.',en:'Around 313 Muslims faced a far larger army and won by Allah’s help.',ar:'نحو ٣١٣ مسلمًا واجهوا جيشًا أكبر بكثير فنُصروا بعون الله.'} },
  { cat:'seerah', level:4, c:0,
    q:{de:'Wie nennt man das Jahr, in dem Khadîja und Abû Ṭâlib starben?',tr:'Hatice ile Ebû Tâlib’in vefat ettiği yıla ne denir?',en:'What is the year Khadîja and Abû Ṭâlib died called?',ar:'ماذا يُسمّى العام الذي توفيت فيه خديجة وأبو طالب؟'},
    o:[{de:'ʿÂm al-Ḥuzn (Jahr der Trauer)',tr:'Hüzün Yılı',en:'ʿÂm al-Ḥuzn (Year of Sorrow)',ar:'عام الحزن'},{de:'ʿÂm al-Fîl',tr:'Fil Yılı',en:'ʿÂm al-Fîl',ar:'عام الفيل'},{de:'ʿÂm al-Fatḥ',tr:'Fetih Yılı',en:'ʿÂm al-Fatḥ',ar:'عام الفتح'},{de:'ʿÂm al-Wafd',tr:'Vüfud Yılı',en:'ʿÂm al-Wufûd',ar:'عام الوفود'}],
    e:{de:'Das „Jahr der Trauer“ – der Prophet ﷺ verlor Frau und beschützenden Onkel und blieb dennoch geduldig.',tr:'“Hüzün Yılı” – Peygamber ﷺ eşini ve koruyucu amcasını kaybetti, yine de sabretti.',en:'The “Year of Sorrow” — the Prophet ﷺ lost his wife and protecting uncle, yet stayed patient.',ar:'«عام الحزن»؛ فقد النبي ﷺ زوجته وعمّه الحامي وصبر.'} },

  /* ===== ʿIbâda & Fiqh ===== */
  { cat:'fiqh', level:1, c:0, ref:'Bukhârî 8',
    q:{de:'Wie viele Säulen hat der Islam?',tr:'İslam’ın kaç şartı vardır?',en:'How many pillars does Islam have?',ar:'كم عدد أركان الإسلام؟'},
    o:[{de:'5',tr:'5',en:'5',ar:'٥'},{de:'6',tr:'6',en:'6',ar:'٦'},{de:'4',tr:'4',en:'4',ar:'٤'},{de:'7',tr:'7',en:'7',ar:'٧'}],
    e:{de:'Fünf: Shahâda, Ṣalâh, Zakât, Ṣawm, Ḥajj (Bukhârî 8).',tr:'Beş: Şehâdet, namaz, zekât, oruç, hac (Buhârî 8).',en:'Five: Shahâda, Ṣalâh, Zakât, Ṣawm, Ḥajj (Bukhârî 8).',ar:'خمسة: الشهادة والصلاة والزكاة والصوم والحج (البخاري ٨).'} },
  { cat:'fiqh', level:1, c:0,
    q:{de:'Wie viele Pflichtgebete gibt es täglich?',tr:'Günde kaç vakit farz namaz vardır?',en:'How many obligatory prayers are there daily?',ar:'كم عدد الصلوات المفروضة في اليوم؟'},
    o:[{de:'5',tr:'5',en:'5',ar:'٥'},{de:'3',tr:'3',en:'3',ar:'٣'},{de:'7',tr:'7',en:'7',ar:'٧'},{de:'6',tr:'6',en:'6',ar:'٦'}],
    e:{de:'Fünf tägliche Gebete: Fajr, Ẓuhr, ʿAṣr, Maghrib, ʿIshâʾ.',tr:'Beş vakit: Sabah, öğle, ikindi, akşam, yatsı.',en:'Five daily prayers: Fajr, Ẓuhr, ʿAṣr, Maghrib, ʿIshâʾ.',ar:'خمس صلوات: الفجر والظهر والعصر والمغرب والعشاء.'} },
  { cat:'fiqh', level:2, c:0,
    q:{de:'Wie hoch ist die Zakât üblicherweise (auf Ersparnisse)?',tr:'Zekât (birikim üzerinden) genelde ne kadardır?',en:'How much is Zakât usually (on savings)?',ar:'كم مقدار الزكاة عادةً (على المال المدّخر)؟'},
    o:[{de:'2,5 %',tr:'%2,5',en:'2.5%',ar:'٢٫٥٪'},{de:'5 %',tr:'%5',en:'5%',ar:'٥٪'},{de:'10 %',tr:'%10',en:'10%',ar:'١٠٪'},{de:'1 %',tr:'%1',en:'1%',ar:'١٪'}],
    e:{de:'2,5 % auf Vermögen, das das Nisâb übersteigt und ein Mondjahr gehalten wurde.',tr:'Nisabı aşan ve bir yıl elde kalan malın %2,5’i.',en:'2.5% on wealth above the Nisâb held for one lunar year.',ar:'٢٫٥٪ على ما بلغ النصاب وحال عليه الحول.'} },
  { cat:'fiqh', level:2, c:0,
    q:{de:'In welchem Monat ist das Fasten Pflicht?',tr:'Oruç hangi ayda farzdır?',en:'In which month is fasting obligatory?',ar:'في أي شهر يجب الصيام؟'},
    o:[{de:'Ramadân',tr:'Ramazan',en:'Ramadan',ar:'رمضان'},{de:'Shaʿbân',tr:'Şaban',en:'Shaʿbân',ar:'شعبان'},{de:'Muḥarram',tr:'Muharrem',en:'Muḥarram',ar:'محرم'},{de:'Rajab',tr:'Recep',en:'Rajab',ar:'رجب'}],
    e:{de:'Das Fasten im Ramadân ist eine der fünf Säulen (al-Baqara 2:185).',tr:'Ramazan orucu beş şarttan biridir (Bakara 2:185).',en:'Fasting in Ramadan is one of the five pillars (al-Baqara 2:185).',ar:'صوم رمضان ركن من الأركان الخمسة (البقرة ٢:١٨٥).'} },
  { cat:'fiqh', level:2, c:0,
    q:{de:'Welches Pflichtgebet hat 3 Rakʿa?',tr:'Hangi farz namaz 3 rekâttır?',en:'Which obligatory prayer has 3 rakʿahs?',ar:'أي صلاة مفروضة ثلاث ركعات؟'},
    o:[{de:'Maghrib',tr:'Akşam',en:'Maghrib',ar:'المغرب'},{de:'Fajr',tr:'Sabah',en:'Fajr',ar:'الفجر'},{de:'ʿAṣr',tr:'İkindi',en:'ʿAṣr',ar:'العصر'},{de:'ʿIshâʾ',tr:'Yatsı',en:'ʿIshâʾ',ar:'العشاء'}],
    e:{de:'Maghrib = 3 Rakʿa; Fajr = 2; Ẓuhr/ʿAṣr/ʿIshâʾ = 4 (Farḍ).',tr:'Akşam = 3; Sabah = 2; Öğle/İkindi/Yatsı = 4 (farz).',en:'Maghrib = 3; Fajr = 2; Ẓuhr/ʿAṣr/ʿIshâʾ = 4 (farḍ).',ar:'المغرب ٣؛ الفجر ٢؛ الظهر/العصر/العشاء ٤ (فرضًا).'} },
  { cat:'fiqh', level:3, c:0, ref:'Bukhârî 1933',
    q:{de:'Was macht das Fasten NICHT ungültig?',tr:'Aşağıdakilerden hangisi orucu BOZMAZ?',en:'Which does NOT break the fast?',ar:'أيٌّ مما يلي لا يُفسد الصوم؟'},
    o:[{de:'Vergessliches Essen',tr:'Unutarak yemek',en:'Eating out of forgetfulness',ar:'الأكل ناسيًا'},{de:'Absichtliches Trinken',tr:'Bilerek içmek',en:'Deliberately drinking',ar:'الشرب عمدًا'},{de:'Absichtliches Essen',tr:'Bilerek yemek',en:'Deliberately eating',ar:'الأكل عمدًا'},{de:'Absichtliches Erbrechen',tr:'Bilerek kusmak',en:'Deliberately vomiting',ar:'التقيّؤ عمدًا'}],
    e:{de:'Wer aus Vergesslichkeit isst oder trinkt, dessen Fasten bleibt gültig (Bukhârî 1933).',tr:'Unutarak yiyip içenin orucu geçerlidir (Buhârî 1933).',en:'Whoever eats or drinks forgetfully, their fast remains valid (Bukhârî 1933).',ar:'من أكل أو شرب ناسيًا فصومه صحيح (البخاري ١٩٣٣).'} },
  { cat:'fiqh', level:4, c:0,
    q:{de:'Wie heißt das freiwillige Nachtgebet (bes. im Ramadân)?',tr:'Gece kılınan nafile namaza (özellikle Ramazan’da) ne denir?',en:'What is the voluntary night prayer (esp. in Ramadan) called?',ar:'ما اسم صلاة الليل النافلة (خاصة في رمضان)؟'},
    o:[{de:'Qiyâm al-Layl / Tarâwîḥ',tr:'Kıyâmü’l-Leyl / Teravih',en:'Qiyâm al-Layl / Tarâwîḥ',ar:'قيام الليل / التراويح'},{de:'Ḍuḥâ',tr:'Kuşluk (Duhâ)',en:'Ḍuḥâ',ar:'الضحى'},{de:'Istikhâra',tr:'İstihâre',en:'Istikhâra',ar:'الاستخارة'},{de:'Kusûf',tr:'Küsûf',en:'Kusûf',ar:'الكسوف'}],
    e:{de:'Das Nachtgebet (Qiyâm), im Ramadân als Tarâwîḥ, ist stark empfohlen.',tr:'Gece namazı (kıyâm), Ramazan’da teravih olarak çok tavsiye edilir.',en:'The night prayer (Qiyâm), in Ramadan as Tarâwîḥ, is highly encouraged.',ar:'قيام الليل، وفي رمضان التراويح، مستحبٌّ مؤكَّد.'} },

  /* ===== Akhlâq & Ḥalâl / Ḥarâm ===== */
  { cat:'akhlaq', level:1, c:0, ref:'Bukhârî 6018',
    q:{de:'Was soll ein Gläubiger laut Hadîth tun – reden oder …?',tr:'Hadise göre mümin ne yapmalı – konuşmalı mı, …?',en:'Per the hadith, a believer should speak good or …?',ar:'بحسب الحديث: ليقل المؤمن خيرًا أو …؟'},
    o:[{de:'Gutes sagen oder schweigen',tr:'Hayır söylesin ya da sussun',en:'say good or stay silent',ar:'ليقل خيرًا أو ليصمت'},{de:'immer reden',tr:'her zaman konuşsun',en:'always speak',ar:'يتكلّم دائمًا'},{de:'nur arabisch reden',tr:'sadece Arapça konuşsun',en:'speak only Arabic',ar:'يتكلّم العربية فقط'},{de:'laut reden',tr:'yüksek sesle konuşsun',en:'speak loudly',ar:'يرفع صوته'}],
    e:{de:'„Wer an Allah und den Letzten Tag glaubt, sage Gutes oder schweige.“ (Bukhârî 6018) – hüte die Zunge.',tr:'“Allah’a ve ahiret gününe iman eden ya hayır söylesin ya sussun.” (Buhârî 6018) – dilini koru.',en:'“Whoever believes in Allah and the Last Day, let him say good or be silent.” (Bukhârî 6018) — guard the tongue.',ar:'«من كان يؤمن بالله واليوم الآخر فليقل خيرًا أو ليصمت» (البخاري ٦٠١٨) – احفظ لسانك.'} },
  { cat:'akhlaq', level:2, c:0, ref:'al-Ḥujurât 49:12',
    q:{de:'Wovor warnt der Qurʾân im Umgang mit anderen?',tr:'Kurʾân, başkalarıyla ilişkide neye karşı uyarır?',en:'What does the Qurʾân warn against with others?',ar:'مِمَّ يحذّر القرآن في التعامل مع الناس؟'},
    o:[{de:'Ghîba – üble Nachrede',tr:'Gıybet',en:'Ghîba – backbiting',ar:'الغيبة'},{de:'Lächeln',tr:'Gülümsemek',en:'Smiling',ar:'الابتسام'},{de:'Grüßen (Salâm)',tr:'Selam vermek',en:'Greeting (Salâm)',ar:'إلقاء السلام'},{de:'Geschenke geben',tr:'Hediye vermek',en:'Giving gifts',ar:'إهداء'}],
    e:{de:'Ghîba (über Abwesende schlecht reden) ist verboten – meide sie (al-Ḥujurât 49:12).',tr:'Gıybet (arkadan konuşmak) haramdır – kaçın (Hucurât 49:12).',en:'Ghîba (speaking ill of the absent) is forbidden — avoid it (al-Ḥujurât 49:12).',ar:'الغيبة محرَّمة فاجتنبها (الحجرات ٤٩:١٢).'} },
  { cat:'akhlaq', level:2, c:0, ref:'Bukhârî 6224',
    q:{de:'Was sagt man laut Sunna nach dem Niesen?',tr:'Sünnete göre hapşırınca ne denir?',en:'Per the Sunnah, what do you say after sneezing?',ar:'ماذا يُقال بعد العطاس بحسب السنة؟'},
    o:[{de:'al-Ḥamdu lillâh',tr:'Elhamdülillah',en:'al-Ḥamdu lillâh',ar:'الحمد لله'},{de:'schweigen',tr:'susmak',en:'stay silent',ar:'السكوت'},{de:'aufstehen',tr:'ayağa kalkmak',en:'stand up',ar:'القيام'},{de:'MâshâʾAllâh',tr:'Mâşâallah',en:'MâshâʾAllâh',ar:'ما شاء الله'}],
    e:{de:'Der Niesende sagt „al-Ḥamdulillâh“, der Hörende „Yarḥamuk Allâh“ (Bukhârî 6224).',tr:'Hapşıran “Elhamdülillah”, duyan “Yerhamükellah” der (Buhârî 6224).',en:'The sneezer says “al-Ḥamdulillâh”, the hearer “Yarḥamuk Allâh” (Bukhârî 6224).',ar:'يقول العاطس «الحمد لله» ويردّ السامع «يرحمك الله» (البخاري ٦٢٢٤).'} },
  { cat:'akhlaq', level:3, c:0, ref:'Bukhârî 33',
    q:{de:'Welches Zeichen kennzeichnet den Heuchler (Munâfiq)?',tr:'Münafığın alâmeti hangisidir?',en:'Which is a sign of the hypocrite (Munâfiq)?',ar:'أي علامة من علامات المنافق؟'},
    o:[{de:'Wenn er spricht, lügt er',tr:'Konuşunca yalan söyler',en:'When he speaks, he lies',ar:'إذا حدّث كذب'},{de:'Er betet viel',tr:'Çok namaz kılar',en:'He prays much',ar:'يكثر الصلاة'},{de:'Er fastet',tr:'Oruç tutar',en:'He fasts',ar:'يصوم'},{de:'Er gibt Zakât',tr:'Zekât verir',en:'He gives Zakât',ar:'يؤدّي الزكاة'}],
    e:{de:'Zeichen des Heuchlers: lügen, Anvertrautes verraten, Versprechen brechen (Bukhârî 33) – hüte dich davor.',tr:'Münafığın alâmetleri: yalan, emanete hıyanet, sözünde durmama (Buhârî 33).',en:'Signs of the hypocrite: lying, betraying trust, breaking promises (Bukhârî 33).',ar:'علامات المنافق: الكذب، وخيانة الأمانة، وخُلف الوعد (البخاري ٣٣).'} },
  { cat:'akhlaq', level:3, c:0, ref:'al-Isrâʾ 17:23',
    q:{de:'Wie sollen wir laut Qurʾân zu den Eltern sein?',tr:'Kurʾân’a göre anne-babaya nasıl davranmalıyız?',en:'How should we treat parents per the Qurʾân?',ar:'كيف نعامل الوالدين بحسب القرآن؟'},
    o:[{de:'mit Iḥsân (Güte)',tr:'ihsan (iyilik) ile',en:'with Iḥsân (kindness)',ar:'بالإحسان'},{de:'mit Strenge',tr:'sertlikle',en:'with harshness',ar:'بالغلظة'},{de:'sie meiden',tr:'onlardan uzak durarak',en:'by avoiding them',ar:'بالإعراض'},{de:'nur wenn sie zahlen',tr:'sadece para verirlerse',en:'only if they pay',ar:'إن أعطوا مالًا فقط'}],
    e:{de:'„…und zu den Eltern Güte.“ (al-Isrâʾ 17:23) – gleich nach dem Tawhîd genannt.',tr:'“…anne-babaya iyilik.” (İsrâ 17:23) – tevhitten hemen sonra zikredilir.',en:'“…and to parents, good treatment.” (al-Isrâʾ 17:23) — mentioned right after Tawhîd.',ar:'«وبالوالدين إحسانًا» (الإسراء ١٧:٢٣) – ذُكر عقب التوحيد مباشرة.'} },

  /* ===== Allgemein ===== */
  { cat:'general', level:1, c:0,
    q:{de:'In welche Richtung beten Muslime?',tr:'Müslümanlar hangi yöne namaz kılar?',en:'In which direction do Muslims pray?',ar:'إلى أي جهة يصلّي المسلمون؟'},
    o:[{de:'zur Kaʿba in Makka',tr:'Mekke’deki Kâbe’ye',en:'toward the Kaʿba in Makkah',ar:'نحو الكعبة في مكة'},{de:'nach Osten',tr:'Doğuya',en:'to the East',ar:'نحو الشرق'},{de:'nach Jerusalem',tr:'Kudüs’e',en:'to Jerusalem',ar:'نحو القدس'},{de:'nach Süden',tr:'Güneye',en:'to the South',ar:'نحو الجنوب'}],
    e:{de:'Zur Qibla – der Kaʿba in Makka (al-Baqara 2:144).',tr:'Kıbleye – Mekke’deki Kâbe’ye (Bakara 2:144).',en:'Toward the Qibla — the Kaʿba in Makkah (al-Baqara 2:144).',ar:'نحو القبلة، الكعبة بمكة (البقرة ٢:١٤٤).'} },
  { cat:'general', level:2, c:0,
    q:{de:'Wie viele Propheten werden im Qurʾân namentlich genannt?',tr:'Kurʾân’da adı geçen kaç peygamber vardır?',en:'How many prophets are named in the Qurʾân?',ar:'كم نبيًّا ذُكر بالاسم في القرآن؟'},
    o:[{de:'25',tr:'25',en:'25',ar:'٢٥'},{de:'12',tr:'12',en:'12',ar:'١٢'},{de:'40',tr:'40',en:'40',ar:'٤٠'},{de:'99',tr:'99',en:'99',ar:'٩٩'}],
    e:{de:'25 Propheten werden namentlich erwähnt – von Âdam bis Muḥammad ﷺ.',tr:'Adı geçen 25 peygamber vardır – Âdem’den Muhammed ﷺ’e.',en:'25 prophets are mentioned by name — from Âdam to Muḥammad ﷺ.',ar:'ذُكر خمسة وعشرون نبيًّا بالاسم – من آدم إلى محمد ﷺ.'} },
  { cat:'general', level:3, c:0,
    q:{de:'Wer war der erste Kalif nach dem Propheten ﷺ?',tr:'Peygamber ﷺ’den sonra ilk halife kimdir?',en:'Who was the first caliph after the Prophet ﷺ?',ar:'من أول خليفة بعد النبي ﷺ؟'},
    o:[{de:'Abû Bakr',tr:'Ebû Bekir',en:'Abû Bakr',ar:'أبو بكر'},{de:'ʿUmar',tr:'Ömer',en:'ʿUmar',ar:'عمر'},{de:'ʿUthmân',tr:'Osman',en:'ʿUthmân',ar:'عثمان'},{de:'ʿAlî',tr:'Ali',en:'ʿAlî',ar:'علي'}],
    e:{de:'Abû Bakr aṣ-Ṣiddîq (r.a.) war der erste der vier rechtgeleiteten Kalifen.',tr:'Ebû Bekir es-Sıddîk (r.a.), dört râşid halifenin ilkidir.',en:'Abû Bakr aṣ-Ṣiddîq (r.a.) was the first of the four Rightly-Guided Caliphs.',ar:'أبو بكر الصديق رضي الله عنه أول الخلفاء الراشدين.'} },
  { cat:'general', level:4, c:0,
    q:{de:'Welche Sure zu lesen ist am Freitag besonders empfohlen?',tr:'Cuma günü okunması özellikle tavsiye edilen sûre hangisidir?',en:'Which sûrah is especially recommended to read on Friday?',ar:'أي سورة يُستحبّ قراءتها يوم الجمعة؟'},
    o:[{de:'al-Kahf',tr:'Kehf',en:'al-Kahf',ar:'الكهف'},{de:'al-Mulk',tr:'Mülk',en:'al-Mulk',ar:'الملك'},{de:'Yâ Sîn',tr:'Yâsîn',en:'Yâ Sîn',ar:'يس'},{de:'ar-Raḥmân',tr:'Rahmân',en:'ar-Raḥmân',ar:'الرحمن'}],
    e:{de:'Das Lesen von Sûrat al-Kahf am Freitag ist in der Sunna empfohlen.',tr:'Cuma günü Kehf sûresini okumak sünnette tavsiye edilir.',en:'Reading Sûrat al-Kahf on Friday is encouraged in the Sunnah.',ar:'قراءة سورة الكهف يوم الجمعة مستحبّة في السنة.'} },
];
